- zscan.go
- zscan_test.go
Empty text or comments in zone format will cause panics. Also add a description.
> add checks to prevent panic when parsing zone text.

- xfr.go
I thought about your comment, indeed there seems to be a simpler fix. I don't know if that's what you had in mind, but it solves the issue I observed.
> xfr: Transfer.Out use a new Msg every time

- client.go
- xfr.go
Also do not reference `ns` in comments: it is an implementation detail of `time.Duration`, users should use time constants (`time.Nanosecond`, `time.Microsecond`, `time.Millisecond`, `time.Second`, etc.)
Just aesthetic :)
> minor clean ups: use time.Second instead of 1e9

- tsig.go
The server I need to sync with requires the use of HMAC-SHA512. Implement that.
> Add support for HmacSHA512 algorithm in TSIG

- dns_test.go
- msg.go
If you have a system with large amounts of copies, these slice
allocations start stacking up. Use a shared slice and then subslice
them with a cap limit so that append works properly.
Also, add a benchmark and test for Msg.Copy
Benchcmp:
benchmark         old ns/op     new ns/op     delta
BenchmarkCopy     1880          1672          -11.06%
benchmark         old allocs     new allocs     delta
BenchmarkCopy     13             11             -15.38%
benchmark         old bytes     new bytes     delta
BenchmarkCopy     528           528           +0.00%
> Used shared backing array for Msg.Copy

- client_test.go
- dns_test.go
- dnssec_test.go
- labels_test.go
- nsecx_test.go
- parse_test.go
- server_test.go
- sig0_test.go
- update_test.go
- xfr_test.go
Convert tests from being t.Log(..) then t.Fail() to just t.Error(...) as t.Error(...) does both and makes it more clear which messages are errors vs information log messages.
> Convert tests from being t.Log(..) then t.Fail() to just t.Error(...)

- xfr.go
The next chunk needs to use the previous MAC
Using this fix, I can successfully verify the signatures of not
only the first but the subsequent envelopes as well.
Patch was proposed by andrewtj in a comment. Kudos !
> Fix TSig check on second DNS message (TCP) #180

- msg.go
CopyTo allows bypassing allocating a new Msg to work towards less allocation GC churn.
> Split Copy into Copy and CopyTo

- dns.go
The maximum size of a DNS message is actually 65535, the largest value that can be expressed as a 16-bit word.
I did a quick pass over the usage of the constant in the library, and the usage seems to be consistent with the intended value, so this change should not cause any edge case regressions.
> Fix off by one error in MaxMsgSize

- server.go
- udp.go
- udp_windows.go
This PR makes the sessionUDP struct exported from the dns package (by renaming it SessionUDP).  This makes it possible for consumers of the library to reuse it when building their own servers and UDP interfaces.
I found exposing it very helpful when building a multi-listen interface server.
> Export SessionUDP

- dnssec.go
Signatures computed on duplicate records are actually considered BOGUS.
> RRSIG.Sign: remove duplicate before signing records as per RFC

- client_test.go
- edns.go
- msg.go
A handful of EDNS options have been standardized, and they each have a type defined in GoDNS.  However there is currently no way a development team can use GoDNS with internally defined options, or with new options that may be proposed in the future.
This change solves the problem by giving users an EDNS0_CUSTOM type to allow clients to send, and servers to receive, custom EDNS options.
See client_test.go for example usage.
> Add support for custom EDNS options in GoDNS.

- README.md
This is tiny fix. It seems doc is already moved to doc.go.
> README update: document has already moved to doc.go

- README.md
tianon's rawdns is a direct, raw DNS interface to the Docker API
> Add tianon/rawdns to the list of projects

- idn/punycode.go
- idn/punycode_test.go
PR corresponding to mentioned issue.
> Addressed #198, correct decoding should only look at last separator.

- dnssec.go
- zscan_rr.go
Since it's easy to forget the `c.Hdr.Rrtype = TypeCDNSKEY` step.
> Add ToCDNSKEY and ToCDS methods (+bugfix)

- client.go
- client_test.go
- server_test.go
Reduce some code duplication by making Exchange() use Client.Exchange().
When performing an Exchange if the query ID does not match the answer ID
return an error.  Also add a test for this condition.
> Check that the query ID matches the answer ID.

- client.go
Make Client's exchange function easier to read by moving timeout logic
into separate functions.
Start the timers closer to where they're used so that time from other
logic doesn't impact the deadlines.
> Cleanup Client.exchange

- xfr.go
When ReadMsg returns an error, we should not try to access the returned structure as it might be nil.
The inIxfr code tries to access "in.Answer", causing a crash.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5dc851]
goroutine 41 [running]:
github.com/miekg/dns.(*Transfer).inIxfr(0xc2127648d0, 0x437bcc, 0xc21678c600)
/mnt/data/xxxxx/third-party/src/github.com/miekg/dns/xfr.go:110 +0x231
created by github.com/miekg/dns.func·073
/mnt/data/xxxxx/third-party/src/github.com/miekg/dns/xfr.go:45 +0xf5
> Fix crash in inIxfr when ReadMsg fails

- README.md
- dns_test.go
- msg.go
- parse_test.go
- types.go
- update_test.go
- zscan_rr.go
Enables direct parsing of CAA records instead of parsing them as RFC3597 records. This allows the [Boulder](https://github.com/letsencrypt/boulder) developers to clear CAA record parsing code out of our code base.
I tested this against *almost* all the CAA records I could find in the wild ([relevant gist](https://gist.github.com/rolandshoemaker/4911f0c39acb25d68e80)) and everything seems to be working correctly...
> Fix CAA parsing

- README.md
The DNS test in TurboBytes Pulse is handled using this library. 
ref: https://github.com/turbobytes/pulse/blob/master/utils/dns.go#L34
Thanks for this awesome library. I use it a lot for small internal projects as well.
> adding TurboBytes Pulse as a user

- defaults.go
- dnssec.go
- dnssec_test.go
Add a sanity check used by RRSig's Sign and Verify functions making sure
that the records they operate on form a valid RRSet (same name, type,
and class).
Add a unit test TestInvalidRRSet that calls RRSig's Sign and Verify
methods with invalid RRSets, and makes sure the correct error is
returned.
> Check that the RRs passed to Sign and Verify form a valid RFC2181 RRSet

- edns.go
- msg.go
Multiple patches for crashing bugs found with go-fuzz. Rewrote some sections entirely. Got rid of the rdlen value while parsing.
> Fuzz rampage!

- server.go
- server_test.go
I've been thinking of adding support for "dnstap" to mesos-dns. Having direct access to the DNS data frames would be *much* more efficient (and accurate) than packing/unpacking Msg objects.
This PR defines additional, optional fields to Server that allow callers to optionally inject pre/post processing for DNS data frames.
> add interfaces to allow packet-level inspection for pre/post processing

- idn/punycode.go
- idn/punycode_test.go
In one of our programs we do a `ToPunycode()` on all URLs to make sure they are properly encoded. 99% of the URLs don't need any encoding but I noticed we are still seeing a lot of heap allocations being done in `punycode.go`. This pull request adds some checks to `ToPunycode()` and `FromPunycode()` to prevent unneeded heap allocations.
`needpuny()` doesn't make any heap allocations as demonstrated by: http://play.golang.org/p/F3u7F4ZILD
> Do simple prechecks to avoid heap allocations

- .travis.yml
If sudo is not needed, Travis will run the builds in a faster containerized architecture.
Removed "-short", added "-race". Wall time loss seems reasonable.
> Travis: -> new architecture; - short mode; + race detector

- dnssec.go
- dnssec_keygen.go
- dnssec_keyscan.go
- dnssec_privkey.go
- dnssec_test.go
- parse_test.go
- sig0.go
- sig0_test.go
This will allow RRSIG.Sign to use generic crypto.Signer implementations.
This is a interface breaking change, even if the required changes are most
likely just type asserions from crypto.PrivateKey to the underlying type or
crypto.Signer.
> Refactor DNSSEC to use crypto.{PrivateKey,Signer}

- msg.go
- parse_test.go
- privaterr.go
- sanitize.go
- sanitize_test.go
Add function that dedups a list of RRs. Work on strings, which
adds garbage, but seems to be the least intrusive and takes the
last amount of memory.
Some fmt changes snook in as well.
> Add Dedup function - take 4 - wip don't merge

- xfr.go
- This allows a user to call `Dial` before they call `Transfer.In`,
thus specifying the attributes of a [Dialer](https://golang.org/src/net/dial.go?s=5630:5708#L17)
before their AXFR
This is what it looks like to use:
```go
d := net.Dialer{LocalAddr: transfer_source}
c, _ := d.Dial("tcp", *master)
dnscon := &dns.Conn{Conn:c}
transfer = &dns.Transfer{Conn: dnscon}
channel, err := transfer.In(message, *master)
```
closes #264
> Allow supplying a Conn in Transfer struct

- zscan.go
I think this is the correct way to use ParseZone().
an 'else' is not strictly necessary but it's nice to not have to break the for loop and deal with the error somewhere else.
> Update ParseZone() documentation

- dnssec.go
- dnssec_test.go
- types.go
Those len() functions should really be autogenerated
> Fix (*HINFO).len() and HINFO canonicalization in rawSignatureData

- client_test.go
- example_test.go
- idn/punycode.go
- parse_test.go
client_test.go:165: ExampleUpdateLeaseTSIG should be niladic
client_test.go:165: ExampleUpdateLeaseTSIG refers to unknown identifier: UpdateLeaseTSIG
parse_test.go:572: ExampleZone refers to unknown identifier: Zone
parse_test.go:802: ExampleGenerate refers to unknown identifier: Generate
exit status 1
example_test.go:34: ExampleDS should be niladic
exit status 1
idn/punycode.go:202: unreachable code
exit status 1
> tidyup a little with the latest golang.org/x/tools/cmd/vet

- client.go
- client_test.go
- msg.go
This Pull Request fixes the `TODO(miek): this isn't the best strategy!` regarding `Truncated` messages received. Instead of just returning no RRs it's now attempting to do as many RRs as possible until it gets an error then returning `ErrTruncated` along with the partial response. This allows someone to naively just check `err != nil` if they didn't know about truncated messages or someone could check if `err == ErrTruncated` additionally and proceed with the truncated response if they're okay with a truncated response.
More realistically, I don't think servers will be returning partial responses (like how skydns removes the `Extra` first), but it supports that. If a non-partial response is returned (that was truncated) then no error is returned. I can make it still return a …
> Instead of removing all RRs on Truncated, attempt to unpack

- server.go
- server_test.go
I think the test is okay. I'm not that familiar with `Server{}` but I'm pretty sure this is the only place a check is needed to fix #286.
> Fix for issue 286 - panic after closing ResponseWriter in server handler

- server_test.go
- udp_linux.go
The call to conn.File() causes Go to call dup() and then set the resulting FD
to be blocking. This sets the FD back to non-blocking, allowing Shutdown() to
work properly.
Fixes #279.
> Set UDP conn to non-blocking on Linux to fix Shutdown()

- README.md
- client.go
- client_test.go
- server.go
- server_test.go
Developed DNS over TLS support as described in draft:
http://tools.ietf.org/html/draft-ietf-dprive-dns-over-tls-02
Tested with Unbound 1.4.22 with the following extra configuration:
```yaml
server:
interface: 127.0.0.1@853
interface: 127.0.0.1@53
access-control: 127.0.0.0/8 allow
verbosity: 4
ssl-service-key: "/etc/unbound/dev.key"
ssl-service-pem: "/etc/unbound/dev.cert"
ssl-port: 853
```
I left the fallback strategy from TLS to normal DNS for who is using the client, as it will need to change the port from 853 to 53.
See #297
> DNS over TLS

- tlsa.go
Subject says all. Minor typo, rendering the function useless.
> Missing dot between service and protocol.

- update.go
- update_test.go
An update msg can have multiple, different prerequests and also multiple, different remove and inserts. The old code did a reset of the ANSWER and AUTHORITY section each time a rrset was added.
Made a slight optimization that the first time an rrset is added, we
take it length as the initial size. Helps for the one-time add cases.
Added test to prevent regressions.
> Fix code around dynamic updates, allowing for multiple prereq/inserts/removals per update

- labels.go
Explicitly mention that the domain s must be valid before
given to these functions.
Fixes: #306
> Improve docs on the label functions

- client.go
Extend the documentation for Exchange to make it clear that it is
the callers responsibility to enable larger buffers.
> Better docs on client buffer size

- tsig.go
- tsig_test.go
These strings are domain names, so we should lowercase them before
using them.
Also add some tests for Tsig generation and verification.
(/ht ldns release).
> TSIG: lowercase algorithm before use

- msg.go
> Len returns the rr len of the uncompressed format.

- defaults.go
Start at the end of the additional section instead of the beginning.
Optionally we only scan the last 2 records, and get rid of the loop
in its entirety.
> Optimize IsEdns0

- edns.go
- edns_test.go
We were off by a value of 15. This fixes it. Hard to come up with a test
as writing and reading it yourself will be consistent.
> Put the correct extended rcode in OPT

- types_generate.go
The previous logic would act incorrectly when this package was vendored into
other packages.
> Use package name more reliably.

- edns.go
This PR sets the return type of method `ExtendedRcode` to `int`, to be consistent with the keys type of `map` [RcodeToString](https://github.com/miekg/dns/blob/89d9c5e74bc17cc9edb5d44d4f2f93a7ac77e365/msg.go#L127), and to close https://github.com/miekg/dns/issues/341.
> set ExtendedRcode return type to int instead of uint8

- dns_bench_test.go
- msg.go
The performance arguments given in #48 and #102 are perfectly valid reasons to not use `crypto/rand` for every message ID but that doesn't mean you have to use the default seed ([which is literally just `1`](https://golang.org/src/math/rand/rand.go#L178)) when using `math/rand`.
This patch simply reads out a random `int64` using `crypto/rand` on package initialization and uses it to seed the default `math/rand` source. While there are obviously other more viable attacks this should make message ID spoofing/prediction much harder when using the default `Id`.
This also changes `id()` to just use a rand `int32` and bound it to the max size of a `uint16` instead of using `time.Now` since it's a relatively easy to guess variable so it shouldn't actually provide that many useful bits (since …
> Seed math/rand with crypto/rand

- client_test.go
- dnssec_keyscan.go
- generate.go
- msg.go
- msg_helpers.go
- sanitize_test.go
- scan.go
- server.go
- tlsa.go
- types.go
This should make the code a little easier to read.
> Use t.Errorf in tests and make the error variable naming more consistent.

- msg.go
- msg_generate.go
- msg_helpers.go
- privaterr.go
- privaterr_test.go
- zmsg.go
Make the reflection types a black list:
CAA, HIP, IPSECKEY, NSEC3, NSEC, SIG, TSIG, URI,
All other types don't use reflection anymore.
Return a pointer to the header when there is no rdata, this restores old
behavior. The rest of the conversion mostly hangs on getting size-hex
right, but then packStruct and packStructValue and the unpack variant
can be killed.
Generate pack and unpack for all embedded types as well.
> Skip reflection for most types

- dns.go
- msg.go
- nsecx.go
- rawmsg.go
- tsig.go
Gut rawmsg.go as most functions are not used. Reword some documentation.
Add more types to be checked for name compression.
> Cleanup and removals

- msg_generate.go
- zmsg.go
When there is no rdata, return the newly created RR with the header
embedded in it. If we only return the header, we changed the
API for Go DNS.
Fixes #379
> zmsg: return empty rr with header

- msg_generate.go
- parse_test.go
- types.go
- zmsg.go
When removing the reflection we inadvertely also removed the code for
handling empty salt values in NSEC3 and NSEC3PARAM. These are somewhat
annoying because the text representation is '-', which is not valid hex.
> Handle empty salt value

- scan.go
This fixes parsing bugs for certain records, mainly NSEC3. Previously a presentation version of the type bit map `A NS CAA` would be parsed as `A NS NS` as `tokenUpper` was not being properly set when setting `token` which mean't the previous value was used instead.
> Always set tokenUpper when setting token

- server.go
This will avoid the panic if the library user inadvertently initializes Server.PacketConn with a nil pointer
https://github.com/docker/docker/issues/28112
Signed-off-by: Santhosh Manohar <santhosh@docker.com>
> Add nil check for interface value in ActivateAndServe

- server.go
In the switch statement srv.Net is matched for tcp6-tls but then compared against tcp6 within the case statement. This causes tcp6-tls to be equivalent to tcp-tls and not specific to IPv6. The `network = "tcp6"` line was previously unreachable.
This change corrects this and ensures tcp6-tls listens on IPv6 only.
> Fix tcp6-tls support in (*Server).ListenAndServe().

- server_test.go
- udp_linux.go
After calling `Shutdown` of DNS server, the bound port still open. It only happens if the DNS server is running on Linux and use UDP.
> adds tests for shutdown bind port

- .travis.yml
- README.md
- Test Go 1.7 instead of 1.5
- Don't use miekg/dns when testing forks
> Improve test suite

- msg.go
`Unpack` should obviously have checks whether the packet has the expected length. But you know that it contains the DNS header if `UnpackMsgHdr` does not return an error. At that point it is safe to unpack the DNS header wire into the `Msg` struct. 
If unpacked, we can test if our name server has the right bits set when encountering bad DNS queries.
> Unpack header bits if message lenght equals offset

- dane.go
- idn/punycode.go
- nsecx.go
- sig0.go
- tsig.go
This pull request introduces some very minor performance improvements and reduces the garbage produced when calling several functions.
The first commit removes an unused bytes.Buffer from dns/idn.encode. The second commit reduces the amount of garbage produced when calling CertificateToDANE, HashName, (*SIG).Sign and TsigGenerate.
No functionality or APIs are changed.
> Improve performance by addressing some low hanging fruit.

- dnssec.go
- dnssec_keygen.go
This pull request introduces some very minor performance improvements and reduces the garbage produced when calling several functions. I missed these when I opened #444.
The first commit reduces the amount of garbage produced when calling (*DNSKEY).ToDS, (*RRSIG).Sign and (*RRSIG).Verify. The second commit improves the performance and reduces the amount of garbage produced when calling (*DNSKEY).Generate with (*DNSKEY).Algorithm is set to an RSA\* constant.
No functionality or APIs are changed.
> Improve DNSSEC performance by addressing some low hanging fruit.

- msg.go
In certain circumstances crypto/rand.Reader will return non-random bytes, see golang/go#11833. The most likely case is near boot, and as init is run when the go program is started, it's possible that a non-random seed could be used. While this is very unlikely to ever be an issue, it is a very easy fix and it is preferable to be resilient.
Instead of seeding the global math/rand rng during init, a separate math/rand.Rand is seeded upon the first call to Id. This also avoids polluting the global math/rand rng which might be seeded elsewhere.
If crypto/rand.Reader fails, math/rand.Int63 will be called to provide a seed. This is better than the current fallback to a seed of 1.
This change introduces no noticeable performance overhead as the global math/rand rng already uses a sync.Mutex …
> Work around golang/go#11833 predictable random issue in Id.

- client.go
My home router only return 1 byte on the initial tcp read of 2 bytes
for the size of the reply. We should read the other byte as well if this
happen.
With this fix, this:
~~~
% ./q -tcp @192.168.1.1 higgs
;; dns: short read
~~~
becomes:
~~~
% ./q -tcp @192.168.1.1 higgs
;; opcode: QUERY, status: NOERROR, id: 12968
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;higgs.	IN	 A
;; ANSWER SECTION:
higgs.	0	IN	A	192.168.1.108
;; query time: 10737 µs, server: 192.168.1.1:53(tcp), size: 44 bytes
~~~
> dns/tcp: more robust read.

- client.go
co.Conn is a net.Conn, and has a Write(b []byte) method on it. So this change will continue to work for net.UDPConn, but now allows for other implementations (such as a appengine.socket.Conn).
> A co.Conn is not always a (*net.UDPConn) so don't convert to it.

- clientconfig.go
- clientconfig_test.go
Instead of forcing users to build the list of queries they should make for a given name (like https://github.com/prometheus/prometheus/blob/master/discovery/dns/dns.go#L171) `ClientConfig` should have a `NameList` function much like https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L360 to get a slice of all the given names.
This would also fix a prometheus bug where they're incorrectly looking at suffixes first instead of trying fqdn if it has ndots. I'll make a PR for that once this is fixed.
> Added NameList function to ClientConfig

- edns.go
Hi,
I was following the example of setting edns-client-subnet option via GoDoc and noticed the struct field was misnamed:
`e.SourceNetMask undefined (type *dns.EDNS0_SUBNET has no field or method SourceNetMask, but does have SourceNetmask)`
> Update GoDoc reference to EDNS0_SUBNET.SourceNetmask field.

- client.go
- client_test.go
The response message must copied regardless of whether there was an
error or not, otherwise two concurrent queries may modify the response
as they write it out.
Thanks @Bplotka @kdima for their work on debugging this race.
> Fix data race in error handling.

- README.md
Quilt is container orchestrator that depends on JavaScript as its
configuration mechanism.  It takes advantage of miekg/dns for name
resolution, and thus should be listed in the README.md file.
> README: Add Quilt to the list of users

- README.md
thinks dns lib for help JD.COM make DNS service for kubernetes cluster
> add use case

- dnssec_keyscan.go
- parse_test.go
- scan.go
- scan_rr.go
I came across an interesting problem where uint field parsing can exhibit some odd behavior when parsing out of bound input. This updates the various functions in `scan_rr` that parse unsigned integers to use `strconv.ParseUint` instead of `strconv.Atoi`, which returns more appropriate errors.
Below is an example highlighting some of the parsing oddities
```go
package main
import (
"fmt"
"github.com/miekg/dns"
)
func main() {
input := []string{
"example.com. 3600 IN MX -1 mail.example.com.",
"example.com. 3600 IN MX 65536 mail.example.com.",
}
for _, inp := range input {
rr, _ := dns.NewRR(inp)
fmt.Println(rr.String())
}
}
```
Which is accepted and yields the following output, instead of an error:
```
example.com.	3600	IN	MX	65535 mail.example.com.
example.com.	3600	IN	MX	0 …
```
> Replace Atoi with ParseUint where appropriate

- msg_generate.go
- zmsg.go
Instead of just not doing it at all.
Fixes #473.
> Only pack NSEC3/NSEC3PARAM salt when it is not empty

- issue_test.go
- msg_helpers.go
I'm not going to fix padding anytime soon so I've rebased the commit I mentioned in #426. Padding should only come in to play if another NSEC3 hash algorithm is introduced so there's no rush to fix it.
> Cover NSEC3 Salt and allow mixed case in NSEC3 NextDomain

- dnssec.go
The large exponent check for RSA on DNSSEC is using `(2^32)` when it should use `(2^32)+1`.
This post was used as reference: https://www.imperialviolet.org/2012/03/17/rsados.html
> Fix large RSA exponent check

- parse_test.go
- scan_rr.go
- types.go
- zcompress.go
- zmsg.go
- ztypes.go
See
https://www.iana.org/assignments/dns-parameters/AVC/avc-completed-template
for the template, a new record that is (again) a mirror of the TXT
record. For lack of a better name, name the rdata Txt - as we do in SPF
and TXT.
> Add AVC record

- labels.go
- labels_test.go
- nsecx.go
- nsecx_test.go
Removes NSEC `Cover` + `Match` functions and the denialer interface and cleans up the same NSEC3 methods to fix all the TODOs. This is a breaking change but given that the NSEC methods were already broken (i.e. only ever returned `false`) if anyone was using them seriously their software was already broken and they should stop. Also adds a table test for `Cover` which checks each of the possible outcomes and a few more tests for `Match`.
Fixes #313.
> NSEC/3 Cover+Match cleanup

- parse_test.go
- scan.go
When done parsing, check if we have balanced braces, if not error out.
Fixes #488
> parsing: error on unbalanced braces

- defaults.go
- response Opcode must match request
- RD and CD semantics are only defined for QUERY
> Fix default response generation

- xfr.go
- xfr_test.go
When the server returns a non succesful rcode, return that to the caller
in stead of the "bad soa" of before. "dns: bad xfr rcode: <RCODE>" is
now returned.
Fixes #467
> xfr: return sane error when !RcodeSuccess

- scan.go
- scan_test.go
when zone files parsed with ParseZone(...) contain $INCLUDE statements the file to be included is never parsed because l := <- c shadows the next occurrence of l.token to open the file.
added testcase as proof, the testcase was created from working backwards from the error. Originally the reported l.token used in os.Open() was "\n".
proposed fix: use switch with a ; to localize the variable
> variable shadowing of token

- scan.go
- scan_test.go
When an $INCLUDE was seen the arguments to parseZone where in the wrong
order meaning the filename was used as the `neworigin` instead of the
actual origin we need.
Extend the testcase to check for the full name of the record.
> scan: Fix $INCLUDE arguments to parseZone

- edns.go
- msg_helpers.go
Fixes #342 (but the RFC 7830 version instead of draft-ietf-dprive-edns0-padding), it's a bit of a weird one.
> Implement EDNS(0) Padding option code

- dnsutil/util.go
- doc.go
- parse_test.go
- privaterr_test.go
- scan.go
- scan_rr.go
Per [RFC 1035](https://tools.ietf.org/html/rfc1035#section-5.1) as updated by [RFC 2308](https://tools.ietf.org/html/rfc2308#section-4):
* Omitted RR TTL values "default to the last explicitly stated values" (unless a $TTL directive has been specified).
* "A relative name is an error when no origin is available"
Fixes #484
> Correctly parse omitted TTLs and relative domains

- CONTRIBUTORS
- internal/socket/cmsghdr.go
- internal/socket/cmsghdr_linux_32bit.go
- internal/socket/cmsghdr_linux_64bit.go
- internal/socket/cmsghdr_other.go
- internal/socket/controlmessage.go
- internal/socket/controlmessage_test.go
- internal/socket/socket.go
- internal/socket/sys.go
- udp.go
- udp_linux.go
- udp_linux_test.go
- udp_other.go
- udp_windows.go
Previously, the oob data was just stored and sent to WriteMsgUDP but it ignores the Src field when writing. Instead, now it is setting the Src to the original Dst and handling IPv4 IPs over IPv6 correctly.
Unfortunately, we still need the Windows-specific file since `ReadMsgUDP` is not implemented in Windows:
```
// BUG(mikio): On NaCl, Plan 9 and Windows, the ReadMsgUDP and
// WriteMsgUDP methods of UDPConn are not implemented.
```
Additionally, `SetControlMessage` is not supported on Windows either.
I've tested nothing broke with Windows, and Linux ipv4/ipv6 works as expected.
> Correctly set the Source IP to the received Destination IP with ipv4/ipv6

- .travis.yml
Bumped Go version to 1.8 and 1.9 to keep in line with the last two releases
> Go version bump in CI

- dns_bench_test.go
- msg.go
This is #519 by @rolandshoemaker with different code.
There is no difference in the speed of `msg.Len` with compression, but there is a noticeable speed up without compression.
I have no idea if this is worth merging or not, but I could see some obvious inefficiencies in that PR and I decided to address them.
```
name                      old time/op  new time/op  delta
MsgLength-8               1.65µs ± 6%  1.65µs ± 6%     ~     (p=0.968 n=10+9)
MsgLengthNoCompression-8   132ns ± 6%    15ns ± 3%  -88.61%  (p=0.000 n=10+10)
```
Original pull request (#519): "Removes a bunch of duplication in the msg.Len path ~and exposes the method used to calculate the compressed length of a RR given a provided compression map~."
> Simplify compressed length code

- edns.go
Do not complain about AddressFamily=0, if SubnetNetmask is also 0.
Fixes issue #529
> Fix EDNS0_SUBNET compatibility with dig

- clientconfig.go
- clientconfig_test.go
This allows projects that use this parser to write unit tests without
writing temporary files to the filesystem.
> Allow parsing resolv.conf from io.Reader

- labels.go
- labels_test.go
Optimize CompareDomainName:
old: BenchmarkCompareDomainName-2   	 1000000	      1869 ns/op	      64 B/op	       2 allocs/op
new: BenchmarkCompareDomainName-2   	 2000000	       854 ns/op	      64 B/op	       2 allocs/op
This removes the strings.ToLower and fixes the documentation. It also
does not Fqdn's the names anymore (the documentation said we didn't, now
the documentation is right again).
Unlike what the documentation said we are comparing in a ignore-case
manor, add helper function equal that does this without calling
strings.ToLower.
> Optimize CompareDomainName

- README.md
The project renamed itself, so this patch updates the relevant link.
> Change quilt.io link in the README to kelda.io

- doc.go
I spent several hours trying to figure out why my TSIG signatures were
failing on requests to a server.  I finally discovered this little
detail in the RFC which turned out to be my whole problem.  Amending the
documentation to hopefully spare others the same confusion.
If an incoming message contains a TSIG record, it MUST be the last
record in the additional section.
RFC2845 3.2
> Document SetTsig() needs to be final RRset change

- compress_generate.go
- edns.go
- zcompress.go
In preparing to remove the length-bytes from some structs (#426) I noticed the output of `compress_generate.go` isn't stable and `edns.go` needs a `go fmt`.
> Make compress generate output stable and edns.go formatting

- client.go
- dns.go
- labels_test.go
- msg.go
- scan.go
- scan_rr.go
Some renames of internal names to make go lint happier.
> Cleanup: gofmt -w -s *.go

- README.md
Remove specifying the versions of Go, just say the last two, this is
getting stale every single time.
> readme: small bunch updates

- .travis.yml
- client_test.go
- dns_bench_test.go
- dns_test.go
- dnssec_test.go
- dnsutil/util.go
- dnsutil/util_test.go
- issue_test.go
- nsecx_test.go
- rr_test.go
- sanitize_test.go
- server_test.go
- update_test.go
Use :0 for loopback testing. This is more portable between testing environments.
Add testRR that calls NewRR and throws error away - apply it everywhere where needed.
> Tests updates

- .travis.yml
- dnsutil/util.go
- dnsutil/util_test.go
Fixes https://github.com/miekg/dns/issues/555
> util.TrimDomainName() fails when origin doesn't end in dot

- client_test.go
- server.go
Drop all graceful handling. There is just too much locking in
waitgrouping going on for very little gain; deal with it.
This actually breaks a test - which I'm looking into.
> server: drop graceful handling

- client_test.go
- server.go
- server_test.go
This drops the waitgroup in Server, the suspicion is this can make the server
fail to stop; doing this make graceful shutdown not work.
Add test that tries to find a race between starting on stopping race;
there was a data race on srv.Inflight.
The coredns' TestReadme doesn't race anymore with this as it did with
the more evasive PR #546.
> Server: drop inflight waitgroup

- dnssec_keyscan.go
- leak_test.go
- parse_test.go
- scan.go
- scanner.go
When a higher level (grammar or syntax) error was encountered the lower
level zlexer routine would be left open. This leaks a goroutine.
This PR fixes this by signalling this error, retrieving any remaining
items from the channel, so zlexer can return.
Fixes #586
Fixes https://github.com/coredns/coredns/issues/1233
> txt parser: fix goroutine leak

- parse_test.go
- scan.go
- server_test.go
Remove the debug.Printf stuff from scanner and some other style nits.
> cleanup: remove debug.Printf from scanner

- client.go
- server.go
- xfr.go
Update the documentation to make clear that the zonename in the TsigSecret map must be in canonical form.
Personally I think the library has to do the canonicalization from string to wire format itself but having the documentation to be clear seems like a good idea in the first place.
> TSIG name must be presented in canonical form

- README.md
- parse_test.go
- scan_rr.go
- types.go
- types_generate.go
- zmsg.go
- ztypes.go
Implement the CSYNC record.
Fixes #290
Long overdue, lets add this record. Similar in vain as NSEC/NSEC3, we
need to implement len() our selves. Presentation format parsing and
tests are done as well.
This is CoreDNS running with CSYNC support, `dig` doesn't support this
at the moment, so:
~~~
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40323
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;csync.example.org.		IN	TYPE62
;; ANSWER SECTION:
csync.example.org.	10	IN	TYPE62	\# 12 000335240042000460000008
;; AUTHORITY SECTION:
example.org.		10	IN	NS	a.iana-servers.net.
example.org.		10	IN	NS	b.iana-servers.net.
~~~
> Implement CSYNC

- dnssec.go
rawSignatureData currently missed a few types:
MD MF RP AFSDB RT SIG PX NXT A6
We don't have NXT and A6 anymore in this lib. Add the other ones.
Fixes #523
> Include missing types when for DNSSEC sig verify

- clientconfig.go
- clientconfig_test.go
My modifications expect that the order of NameList matches the order of requests to dns
miekg. miekg.test. 
will be queried in exact this order.
miekg should be queried before miekg.test. so the dns has got the capability to give an answer to this (as docker in swarm mode does)
> Modified clientconfig to match ndots0

- dns_test.go
- scan_rr.go
- types.go
- zmsg.go
- make sure Key and Data fields are variable length hex fields
- checkin output from 'go generate'
- add a TKEY specific test to ensure this stays working
> Add support for TKEY RRs

- README.md
- edns.go
- msg_helpers.go
Noone should be using this option, it has been deprecated ever since
RFC 7178 came out: May 2016. Remove code that deals with that.
> EDNS0 client subnet: drop draft option

- Makefile.release
- version.go
- version_test.go
Add a version.go that has the semver version of this libary; now at
1.0.0. Use a struct so external code can easily check the for the
version without resulting to string parsing. Add String() function if
you want to access the version string.
Fixes #592
> Add semver

- dns_test.go
- types_generate.go
- ztypes.go
This was missing and generated the wrong code for TKEY; it adds a +1 to
the amount. This should happen (technically).
I think the fallout is not super bad (of the +1) as we allocate a byte
more for when pack a message.
> Add size-hex: modifier for len()

- scan.go
When using a relative file in an $INCLUDE the file is referenced from
the cwd from the calling processes; this changes it to be down from the
view point where the file exists.
Code from https://github.com/miekg/dns/issues/537#issuecomment-342932962
Fixes #537
> Allow $INCLUDE to reference relative file

- scan.go
If you take the effort of creating includePath, actually use it when
opening the file. Now tested (again) with CoreDNS (with a zone file that
includes two others)
Failure to include leads to:
~~~
2017/12/07 16:47:00 plugin/file: /tmp/example.org: dns: failed to include `a/1include1.org' as `/tmp/a/1include1.org': "a/1include1.org" at line: 15:24
~~~
> relative include: now tested!

- client_test.go
- msg.go
When we unpack a message and only have the header consider it a valid
message and don't return an error.
> Unpack: return header

- msg.go
We currently use information from a potential attacker to pre-allocate slices for the Question, Answer, etc. sections. This allows an attacker to force allocation of several MiB per parsed Msg.
Instead, don't pre-allocate those slices. append() always allocates in powers of two, which is probably the best we can do.
Fixes #609.
> Don't use untrusted lengths from Header to pre-allocate

- server.go
I tested this quickly in production. Can confirm io timeout from deadlines is err.Temporary() == true and use of closed connection is not opError, so it works in prod for me.
> Fixes #613

- defaults.go
- parse_test.go
- scan.go
- update_test.go
Class "ANY" is wireformat only. In zonefile you can use CLASS255, but
when String-ing we convert this into "ANY" which is wrong. I.e. this
means we can't read back our own update.
Bit of a kludge to work around this, as I'm not sure we can just remove
ANY from the ClassToString map.
> ClassANY: don't convert CLASS255 to ANY

- server.go
The check for `srv.started` being false is in the wrong place, it should be after `Accept` not after `ReadTCP`. If `Shutdown` is called, `serveTCP` will currently return a 'use of closed network connection' error, which is undesired.
This commit mirrors the behaviour of `serveUDP` with respect to `Shutdown`.
> Fix TCP Shutdown 'use of closed network connection'

- server.go
serveTCP calls reader.ReadTCP in the accept loop rather than in
the per-connection goroutine. If an attacker opens a connection
and leaves it idle, this will block the accept loop until the
connection times out (2s by default). During this time no other
incoming connections will succeed, preventing legitimate queries
from being answered.
This commit moves the call to reader.ReadTCP into the per-connection
goroutine. It also adds a missing call to Close whose absence allowed
file-descirptors to leak in select cases.
This attack and fix have no impact on serving UDP queries.
> Fix for CVE-2017-15133 TCP DOS

- server_test.go
This test checks that calling `Shutdown` does not cause `ActivateAndServe` (via `serveTCP` and `serveUDP`) to return the underlying 'use of closed network connection' error.
This commit unifies `TestShutdownTCP` with `TestShutdownUDP`. After this commit, both tests will check that `ActivateAndServe` returns a nil error and that `Shutdown` succeeded.
This was previously broken for `serveTCP` (#623).
I didn't add this to `TestShutdownTLS` as the shutdown path is identical to TCP, but I can add it to this pull request if desired.
> Test that Shutdown does not surface closed errors

- clientconfig.go
- clientconfig_test.go
Fix panic when option have a len of 8 on `attempts` parsing.
```console
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/containous/traefik/vendor/github.com/miekg/dns.ClientConfigFromFile(0x211b1eb, 0x10, 0x0, 0x0, 0x0)
/go/src/github.com/containous/traefik/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.getNameservers(0x211b1eb, 0x10, 0x32e9920, 0x2, 0x2, 0x92d9bc, 0xc4202240e0, 0x1)
/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.init()
/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d …
```
> fix: panicing on options parsing.

- server.go
As part of trying to solve #646 I decided to cleanup the `(*Server).serve` function and make it more idiomatic. In doing that I split it up into separate functions for UDP and TCP, and split out the code for invoking `ServeDNS`. There should be no changes in functionality or behaviour.
This pull request is split across several commits to make it easier to follow along.
> Cleanup serve function

- doc.go
ExchangeWithDialer is in the godoc, but its not valid.  This changes it to the appropriate client dialer setting and `c.Exchange` call.
> ExchangeWithDialer does not exist anymore

- udp_test.go
See https://github.com/miekg/dns/issues/660 for rationale and discussion.
> Skip UDP OOB tests on unsupported architectures

- dns.go
- dnssec.go
- privaterr.go
- types_generate.go
- ztypes.go
copyHeader() is redundant, we allocate a header and then copy the
non-pointer elements into it; we don't need to do this, because if we
just asssign rr.Hdr to something else we get the same result.
Remove copyHeader() and the generation and use of it in ztypes.go.
> copyHeader is redundant

- msg.go
- msg_test.go
When the message has an EDNS0 option in the additional section and
dns.Msg.Rcode is set to an extended rcode, dns.Msg.PackBuffer() modifies
dns.Msg.Rcode.
If you were to `Pack` the message and log it after, the Rcode would show
NOERROR.
Running the test before the change would error with:
```
=== RUN   TestPackNoSideEffect
--- FAIL: TestPackNoSideEffect (0.00s)
msg_test.go:51: after pack: Rcode is expected to be BADVERS
```
after fixing dns.Msg.PackBuffer(), all tests are still passing.
Fixes #674
> do not modify dns.Rcode when packing to wire format

- nsecx_test.go
- scan_rr.go
This fixes #676 and should be non-invasive.
/cc @shadrick
> Handle empty NSEC3 salt in scanner

- client.go
- client_test.go
- leak_test.go
This is my third attempt at adding DNS-over-HTTPS support to `Client.`. It supersedes #647, #649 and #651.
This method provides DNS-over-HTTPS support exclusively within the `(*Client).Exchange*` APIs.
It's proving difficult to pipe cancellation and context through the `Client`, and I suspect some refactoring will be needed.
Note: when using DNS-over-HTTPS, the `Dialer`, `TLSConfig` and `*Timeout` (*todo*) fields on `Client` are ignored.
> WIP: DNS-over-HTTPS support for Client.Exchange API

- edns.go
Previous behavior was correct. Checking with coredns:
current:
~~~
; <<>> DiG 9.10.3-P4-Debian <<>> +norec +noad +edns=1 +noednsneg soa miek.nl @localhost -p 1043
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: ?256, id: 35480
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; Query time: 0 msec
;; SERVER: ::1#1043(::1)
;; WHEN: Sat May 19 16:42:54 BST 2018
;; MSG SIZE  rcvd: 23
~~~
this pr:
~~~
; <<>> DiG 9.10.3-P4-Debian <<>> +norec +noad +edns=1 +noednsneg soa miek.nl @localhost -p 1043
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: BADVERS, id: 25912
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, …
> Revert 6f3c0a126ca15bec6b0db0c77e65ed4ad2354ca2

- msg_helpers.go
The base32 variant NSEC3 uses doesn't have padding. This hasn't been a
problem in practice because SHA1 is the only current NSEC3 hash algorithm
and its output doesn't require padding.
No-pad support was introduced in Go 1.9 which is the oldest release this
package supports.
---
This is a follow up to the discussion in #426.
> Don't use padding in base32 helpers

- client.go
- client_test.go
DoH support now requires the full URL to be passed to `Exchange` rather than just the hostname.
This is to accommodate the (unfortunate) removal of the `.well-known/dns-query` path in draft-ietf-doh-dns-over-https-03, see https://www.ietf.org/rfcdiff?url1=draft-ietf-doh-dns-over-https-02&url2=draft-ietf-doh-dns-over-https-03&difftype=--html.
DNS-over-HTTPS support now works as:
```go
(&Client{Net: "https"}).Exchange(new(Msg), "https://dns.cloudflare.com/dns-query")
```
> Require URLs for DOH addresses

- client.go
See issue #689
- I change the dial function, setting the timeout for dialing based on dialTimeout() instead of writeTimeout().
- Update the direct public functions DialTimeout(..) and DialTimeoutWithTLS(..), passing the dialTimeout to the client, because these functions creates a client on the fly to operate the Dial.
> Fix DialTimeout for direct call of Dial 

- dnssec.go
- dnssec_test.go
The first two commits add the test from #688 and a fix for that issue.
The third one adds an early return if the exponent's length exceed 4 bytes because the crypto package requires the exponent to fit into 32-bits. It also alters the size check to use the [same value as the crypto package](https://github.com/golang/go/blob/41dd2ebcee5652571f8cfa924597e67f3ddb6111/src/crypto/rsa/rsa.go#L79-L81).
> Fix unpacking RSA exponent and tighten exponent validation

- client_test.go
- dns_test.go
This clears up the travis output some more and adheres to the Unix
saying: no output is good news
> tests: remove t.Log(f) when nothing is failing

- generate.go
- generate_test.go
- scan_test.go
Correctly handle `$GENERATE` modifiers. The width and type (aka base)
components of a modifier are optional. This means that `${2,0,d}`, `${2,0}` and `${2}` are
valid modifiers, however only the first format was previously permitted. Use default
values for the width and/or type if they are unspecified in the modifier.
While here improve test coverage by adding tests for parsing zones with `$GENERATE` and the `modToPrintf` used by `$GENERATE`.
Fixes issue #702
> Correctly handle $GENERATE modifiers

- dnssec_keyscan.go
- dnssec_privkey.go
This was added in golang/crypto@5ba7f63082 and can replace the workaround from #458 / #591.
> Use RFC 8032 functions added to x/crypto/ed25519

- .travis.yml
tip now points to what will be go1.11 leaving go1.10 untested.
> Add go1.10.x to Travis

- server.go
This simplifies the two calls to `srv.lock.Unlock` in both `ListenAndServe` and `ActivateAndServe`, and removes the need to relock the mutex before the return.
It also fixes the case where one of either `serveUDP` or `serveTCP` panics causing `Unlock` to be called twice and that panic clobbering the original panic message. *(Note this has not been actually observed to happen).*
> Simplify unlocking dance in *Serve functions

- client.go
- client_test.go
- dns_test.go
- dnssec.go
- edns.go
- labels.go
- msg.go
- msg_helpers.go
- scan_rr.go
- server.go
- types.go
These were caught with:
```bash
gofmt -r '(a) -> a' -w *.go
```
---
I decided to exclude the following change because, although it is correct, it doesn't look as clear to me. I can include it if you disagree.
```diff
diff --git a/msg_helpers_test.go b/msg_helpers_test.go
index adceb882c5..dccc539248 100644
--- a/msg_helpers_test.go
+++ b/msg_helpers_test.go
@@ -92,7 +92,7 @@ func TestPackDataNsec(t *testing.T) {
for _, tt := range tests {
t.Run(tt.name, func(t *testing.T) {
got, err := packDataNsec(tt.args.bitmap, tt.args.msg, tt.args.off)
-                       if (err != nil) != tt.wantErr {
+                       if err != nil != tt.wantErr {
t.Errorf("packDataNsec() error = %v, wantErr %v", err, tt.wantErr)
return
}
```
> Remove redundant parenthesis

- server_test.go
At present, these benchmarks don't actually work or measure anything. `SetQuestion` must have a fully qualified domain name (trailing dot) to be valid. Because the question wasn't valid, the request never reached the server and was rejected by the client.
With the error check added, the benchmarks started failing with:
```
--- FAIL: BenchmarkServe
server_test.go:346: Exchange failed: dns: domain must be fully qualified
```
> Fix Serve benchmark failures

- server.go
This pull request reduces the memory usage of the UDP server by using a `sync.Pool`.
This is the result of the server benchmarks (with #734):
```
name              old time/op    new time/op    delta
Serve-12            48.7µs ± 3%    50.3µs ± 2%   +3.36%  (p=0.000 n=10+9)
Serve6-12           49.4µs ± 2%    50.8µs ± 3%   +2.80%  (p=0.000 n=10+10)
ServeCompress-12    50.9µs ± 2%    52.9µs ± 3%   +3.87%  (p=0.000 n=10+10)
name              old alloc/op   new alloc/op   delta
Serve-12            3.86kB ± 0%    3.39kB ± 0%  -12.36%  (p=0.000 n=10+10)
Serve6-12           3.70kB ± 0%    3.23kB ± 0%  -12.90%  (p=0.000 n=10+10)
ServeCompress-12    4.12kB ± 0%    3.64kB ± 0%  -11.58%  (p=0.000 n=10+10)
name              old allocs/op  new allocs/op  delta
Serve-12              56.0 ± 0%      56.0 …
```
> Reduce UDP server memory usage

- client.go
This isn't a functional change, but it does leave `(*Client).Dial` cleaner and more readable IMHO.
> Simplify (*Client).Dial handling of network type

- server_test.go
If `Shutdown` returns an error, then `TestServerStartStopRace` will panic because `t.Fatal` is called in a different goroutine. This pull request fixes this, preventing a panic in this case.
```
--- FAIL: TestServerStartStopRace (0.00s)
server_test.go:856: could not stop server: close udp [::]:52229: use of closed network connection
server_test.go:856: could not stop server: close udp [::]:42807: use of closed network connection
server_test.go:856: could not stop server: close udp [::]:40527: use of closed network connection
server_test.go:856: could not stop server: close udp [::]:46957: use of closed network connection
server_test.go:856: could not stop server: close udp [::]:44677: use of closed network connection
server_test.go:856: could not stop server: close udp [::]:46759: use of …
```
> Fix TestServerStartStopRace calling t.Fatal on wrong goroutine

- server.go
- server_test.go
This allows a server to make decision wether or not the link used to
connect to the DNS server is using TLS.
This can be used by the handler for instance to (but not limited to):
- log that the request was TLS vs TCP
- craft specific responsed knowing that the link is secured
- return custom answers based on client cert (if provided)
...
Fixes #711
> [tls] Carry TLS state within (possibly) response writer

- listen_go111.go
- listen_go_not111.go
`unix.SO_REUSEPORT` isn't defined for solaris (or some other non-windows platforms).
The format for build constraints is confusing IMHO, but I'm pretty certain these are correct [[ref]](https://golang.org/pkg/go/build/#hdr-Build_Constraints).
I've confirmed this now builds for solaris/amd64 (cross-compiled from linux/amd64).
This fixes #747.
> Use correct build constraints for listen_*.go files

- msg.go
These two functions were identical (sans-variable names) before I optimized `unpackString` in 5debfeec63 (#746).
This will improve the performance of it's only caller `unpackTxt` and is covered by the test and benchmark added in 5debfeec63.
> Replace unpackTxtString with identical unpackString

- server.go
- server_test.go
w.msg was being prematurely cleared prior to use by TsigVerify in server.go
Analysis in miekg/dns#748
> Bugfix for miekg/dns#748

- msg_helpers.go
- msg_helpers_test.go
This case previously differed from `UnpackDomainName` in msg.go and both `sprintTxtOctet` and `appendTXTStringByte` in types.go and was incorrect.
32 is ASCII space and 126 is ASCII tilde, with 127 being DEL. This was obviously meant to be `>=` but this is consistent with the format of types.go.
> Fix unpackString bug: 127 DEL is unprintable

- serve_mux.go
- serve_mux_test.go
This is several changes to `ServeMux` in one PR:
- The zero `ServeMux` is now usable, `NewServeMux` doesn't need to be called.
- A series of documentation changes.
- Changes to make `ServeMux.ServeDNS` more readable.
- Performance improvements, and simplification, in `ServeMux.match`. Note this is complicated somewhat by ^1.
```
name                   old time/op    new time/op    delta
MuxMatch/lowercase-12     108ns ± 3%      68ns ± 2%   -36.94%  (p=0.000 n=10+10)
MuxMatch/uppercase-12     111ns ± 3%     120ns ± 1%    +7.34%  (p=0.000 n=9+10)
name                   old alloc/op   new alloc/op   delta
MuxMatch/lowercase-12     32.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
MuxMatch/uppercase-12     32.0B ± 0%     32.0B ± 0%      ~     (all equal)
name                   old …
```
> Rework and optimise ServeMux

- server.go
- server_test.go
Calling any of `Write`, `LocalAddr` or `RemoteAddr` after calling `Close` on a TCP connection will cause a panic like the following:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93e4db]
goroutine 129363104 [running]:
github.com/miekg/dns.(*SessionUDP).RemoteAddr(...)
/build/go/src/github.com/miekg/dns/udp.go:34
github.com/miekg/dns.(*response).RemoteAddr(0xc0025ebdd0, 0xc0001d6a80, 0xc000952d72)
/build/go/src/github.com/miekg/dns/server.go:773 +0x5b
```
This pull request adds explicit panics in each of these functions. An alternative is to make `LocalAddr` and `RemoteAddr` to return valid results after `Close`, but this is more explicit at least until such a decision is made.
Updates #766
/cc …
> Explicitly panic after (*response).Close

- msg.go
- msg_test.go
This clears the tainted part of the message before writing the compression pointer.
This includes a test case ported from the original issue.
Fixes #741
/cc @cesarkuroiwa
> NSEC type bitmap packing bug

- server.go
The `(*Server).readTCP` and `(*Server).readUDP` methods both call `SetReadDeadline`. If they race with `ShutdownContext`, they can override the `aLongTimeAgo` read deadline that is set in `ShutdownContext`. That will cause `ShutdownContext` to hang or timeout.
~:crossed_fingers: Let's see if this works.~
Updates #756
Updates #763
> Avoid overriding aLongTimeAgo read deadline

- msg.go
- msg_helpers.go
- types.go
- types_test.go
This is #746 but for the `sprintX` functions in types.go. It follows the same principal.
There is a lot of overlap between these functions and I was hoping to merge them together, but it seemed like too much effort because they were all just a little too different from each other.
```
name               old time/op    new time/op    delta
SprintName-12         247ns ± 3%     218ns ± 3%  -11.54%  (p=0.000 n=9+10)
SprintTxtOctet-12     199ns ± 7%     198ns ±14%     ~     (p=0.780 n=10+10)
SprintTxt-12          384ns ± 6%     257ns ± 7%  -33.03%  (p=0.000 n=10+10)
UnpackString-12       101ns ± 6%     112ns ± 9%  +10.43%  (p=0.000 n=19+10)
name               old alloc/op   new alloc/op   delta
SprintName-12         80.0B ± 0%     48.0B ± 0%  -40.00%  (p=0.000 n=10+10)
SprintTxtOctet-12 …
```
> Optimise sprintX functions in types.go

- generate.go
- generate_test.go
Although BIND9 documentations does not specify the possible size of offset
in $GENERATE clause, it clearly says that range must be a positive integer
between 0 and (2^31)-1. Moreover, BIND perfectly supports large offsets
which might be really handy when you're dealing with large intranets. I.e.
consider following case
```
$GENERATE 0-255 dhcp-${0,4,d}   A 10.0.0.$
$GENERATE 0-255 dhcp-${256,4,d} A 10.0.1.$
$GENERATE 0-255 dhcp-${512,4,d} A 10.0.2.$
...
```
This change removes offset size check and introduces check that
0 >= (start + offset) and (end + offset) < (2^31)-1.
> Allows larger offset in $GENERATE

- server_test.go
This prevents a panic I observed while working on fixing the graceful shutdown hang.
> Prevent a checkInProgressQueriesAtShutdownServer panic

- server_test.go
I'm worried that goroutine scheduling might cause the `"ShutdownContext returned before replies"` check to be flaky. This should avoid goroutine scheduling issues and it's less code.
Updates #761
> Use an atomic int32 in checkInProgressQueriesAtShutdownServer

- server.go
It seems I was very much on the right track with #774, but the race was still there. This *should* finally solve the problem and make graceful shutdown more reliable and not hang like before.
Like I did in #774, I'm going to run the Travis build a few times and see if anything trips.
~This does introduce a lock where there previously wasn't so it could negatively affect performance, that being said, only a read lock is held during the critical path which shouldn't cause any lock congestion.~ (Edit: no it doesn’t, `isShutdown` already held the same lock).
Fixes #756
Closes #761
Closes #763
Closes #771
Updates #774
> Hold srv.lock while calling SetReadDeadline

- .travis.yml
This halves the number of Travis builds that will run, while adding coverage testing to the `dnsutil` package.
> Test coverage for all packages and merge Travis builds

- dnssec_keyscan.go
- generate.go
- generate_test.go
- scan.go
- scan_test.go
This is a pretty large pull request, but again it's ultimately rather simple. The `parseZone` goroutine is eliminated and replaced with a new `ZoneParser` type with a simple chan-like API. This eliminates the goroutines and the 10,000 element buffered `parseZone` chan, which will substantially reduce memory usage.
Errors such as #786 should be impossible with the new API.
`ParseZone` maintains the same semantics as previous, including using a buffered chan of 10,000 elements. It is now a wrapper around the `ZoneParser` API.
The API (minus the `SetX` methods) was discussed in https://github.com/miekg/dns/issues/786#issuecomment-429630595.
~**Note:** This pull request contains an API change. `NewRR` and `ReadRR` no longer support the `$INCLUDE` directive. See the `SetIncludeAllowed` comment …
> Add new ZoneParser API

- server.go
- server_test.go
This refactors how `response.Close` works. This fixes both the memory leak observed in #807 and a similar memory leak that would occur if `Close` was called manually by the handler. The `checkInProgressQueriesAtShutdownServer` test now checks the tracking map is empty after `ShutdownContext` returns.
Along for the ride are some changes to which `response` methods ~panic-after-`Close`~ (edit: fail-after-`Close`), this fixes #766 and allows `LocalAddr` and `RemoteAddr` to work after `Close`.
`Close` also now returns an error if called multiple times.
Fixes #807
Fixes #766
Updates #769
> Fix TCP connection tracking memory leak

- nsecx.go
- nsecx_test.go
I got a NX record (219.50.238.170.virbl.dnsbl.bit.nl) but looks like not covering in `(*NSEC3).Cover()` 
I checked on http://dnsviz.net/d/219.50.238.170.virbl.dnsbl.bit.nl/dnssec/ wildcard hash covered and valid. 
RFC 5155 section 8.4 (https://tools.ietf.org/html/rfc5155#section-8.4) described this.
Can you check it?
> nsec3 cover problems

- edns.go
- edns_test.go
- msg.go
- msg_test.go
When calling `SetExtendedRcode`, we expect to get the full extended
rcode, not the rcode after we shift 4 bytes right.
> properly set extended rcode when packing

- dnssec.go
- sig0.go
`strings.ToLower` may allocate and will do more work than `strings.EqualFold`.
> Use strings.EqualFold rather than strings.ToLower

- edns.go
- edns_test.go
This should be faster than the manual loop and avoids constructing the IP address twice for the IPv6 case.
This was pulled out of #818.
> Use copy instead of loop in EDNS0_SUBNET.unpack

- dns_bench_test.go
- length_test.go
- msg.go
This avoids creating the compression map, and associated garbage, when the `Msg` only has one question.
~This needs to wait on both #821 & #822, and will probably need to be rebased~.
```
$ benchstat {old,new}.bench
name                       old time/op    new time/op    delta
MsgLength-12                  335ns ± 3%     324ns ± 0%    -3.53%  (p=0.000 n=10+9)
MsgLengthNoCompression-12    9.46ns ± 0%    9.46ns ± 1%      ~     (p=0.623 n=9+9)
MsgLengthPack-12             1.91µs ±31%    2.14µs ±16%      ~     (p=0.219 n=10+9)
MsgLengthOnlyQuestion-12      165ns ± 2%       5ns ± 3%   -96.74%  (p=0.000 n=10+10)
PackMsg-12                   1.59µs ±20%    1.56µs ± 6%      ~     (p=0.905 n=10+9)
PackMsgOnlyQuestion-12        757ns ±33%     232ns ± 4%   -69.28%  (p=0.000 n=10+10)
name …
```
> Avoid creating compression map for question only Msg

- msg_helpers.go
Unfortunately there doesn't seem to be any tool to catch these on mass, so this will have to do.
This was pulled out of #818.
> Remove pointless cast from unpackUint48

- msg.go
- reverse.go
[RFC 6895](https://tools.ietf.org/html/rfc6895#page-5) lists RCODE 4 as NotImp.
This PR also continues to support the legacy spelling `NOTIMPL` in `StringToRcode`.
Fixes #733.
/cc @bcorijn
> Fix NotImp RCode string

- compress_generate.go
- dns_bench_test.go
- length_test.go
- msg.go
- zcompress.go
`map[string]int` requires 8 bytes per entry to store the unused position information.
~I couldn't get any clean benchmarks from this, but `map[string]struct{}` definitely uses less memory than `map[string]int`.~
This does unfortunately make the related test cases slightly weaker as they no longer test that the `Len` code is finding compression points in the correct spot.
Updates #709.
Edit: I was able to get some better benchmarks that show a very notable improvement in memory use.
```
$ benchstat {old,new}.bench
name                       old time/op    new time/op    delta
MsgLength-12                  329ns ± 0%     328ns ± 0%   -0.27%  (p=0.040 n=9+9)
MsgLengthNoCompression-12    9.37ns ± 1%    9.34ns ± 2%     ~     (p=0.099 n=10+10)
MsgLengthPack-12             2.26µs ± 9%    2.36µs …
```
> Use map[string]struct{} for compression map in Len

- msg.go
- msg_test.go
The comment should explain my rational for sizing the constant. The added test case now passes.
Fixes #834
> Fix "too many compression points" for valid message

- msg.go
- msg_test.go
This PR drastically reduces the amount of garbage created in `UnpackDomainName` for certain malicious names.
The wire formatted name
```go
"\x3Faaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuu\xC0\x00"
```
would previously generate 1936B of garbage before #835, and 36112B of garbage since #835, before returning the `"too many compression pointers"` error, while after this PR it will generate just 384B of garbage before returning the error.
Related #835
Fixes #836
> Bail early from UnpackDomainName when name is too long

- acceptfunc.go
- msg.go
- server.go
- server_test.go
Generalize the srv.Unsafe and make it pluggeable. Also add a default
pass function that allows to discard of a malformed DNS message very
early on.
Note this makes srv.Unsafe a noop - wondering if we should remove it out right as the next release will be breaking anyway.
> Add MsgAcceptFunc

- length_test.go
- msg.go
- msg_test.go
After this PR, the escaped form of the name will be inserted into the compression map rather than the partially unescaped form. This is slightly non-optimal as certain names won't compress even though they're identical, this could be improved in future, but it's not a bug as compression is purely optional.
This only partially addresses #841, the rest of it will be fixed in a follow up PR once #833 has been merged.
Updates #841
> Put escaped names into compression map

- nsecx.go
- nsecx_test.go
This reduces the memory consumption of `HashName` and makes it slightly cleaner.
```
name               old time/op    new time/op    delta
HashName/150-12      21.2µs ± 2%    20.4µs ± 1%   -3.72%  (p=0.000 n=9+10)
HashName/2500-12      333µs ± 1%     332µs ± 1%     ~     (p=0.165 n=10+10)
HashName/5000-12      663µs ± 1%     668µs ± 2%     ~     (p=0.123 n=10+10)
HashName/10000-12    1.32ms ± 1%    1.33ms ± 1%     ~     (p=0.190 n=9+9)
HashName/65535-12    8.63ms ± 1%    8.61ms ± 1%     ~     (p=0.243 n=10+9)
name               old alloc/op   new alloc/op   delta
HashName/150-12      4.57kB ± 0%    0.48kB ± 0%  -89.49%  (p=0.000 n=10+10)
HashName/2500-12     4.57kB ± 0%    0.48kB ± 0%  -89.49%  (p=0.000 n=10+10)
HashName/5000-12     4.57kB ± 0%    0.48kB ± 0%  -89.49%  (p=0.000 n=10+10) …
```
> Reduce memory consumption in HashName

- msg.go
Simplify unprintable handling in `UnpackDomainName`.
These benchmarks were taking after #844 and show a modest improvement:
```
name                                   old time/op    new time/op    delta
UnpackDomainName-12                       122ns ± 4%     125ns ± 4%    ~     (p=0.052 n=10+10)
UnpackDomainNameUnprintable-12            149ns ± 1%     138ns ± 4%  -7.51%  (p=0.000 n=10+10)
UnpackDomainNameLongest-12                552ns ± 2%     550ns ± 5%    ~     (p=0.403 n=10+10)
UnpackDomainNameLongestUnprintable-12    2.96µs ± 1%    2.70µs ± 1%  -8.74%  (p=0.000 n=10+10)
name                                   old alloc/op   new alloc/op   delta
UnpackDomainName-12                       64.0B ± 0%     64.0B ± 0%    ~     (all equal)
UnpackDomainNameUnprintable-12            48.0B ± 0% …
```
> Simplify unprintable handling in UnpackDomainName

- dns_bench_test.go
- msg.go
- msg_test.go
This simple change greatly improves the performance and memory consumption of `UnpackDomainName`. It's perfectly safe to size `s` this large as it never escapes and will be stack allocated.
After this PR, `UnpackDomainName` will never be the source of memory garbage.
In terms of number of allocations and allocated memory, this is absolutely the best possible results, *i.e.* `UnpackDomainName` can never be more efficient with regards to memory usage.
```
name                                   old time/op    new time/op    delta
UnpackDomainName-12                       169ns ±13%     167ns ±19%     ~     (p=0.955 n=10+10)
UnpackDomainNameUnprintable-12            150ns ±13%     160ns ± 6%   +6.61%  (p=0.015 n=10+10)
UnpackDomainNameLongest-12               1.45µs ±30%    0.74µs ± 7% …
```
> Reduce allocations in UnpackDomainName by better sizing slice

- msg.go
- msg_helpers.go
- types.go
This PR replaces the `strconv.AppendInt` based unprintable octet escaping with pre-calculated table-lookups. This is also much simpler. It also eliminates the duplication between `writeEscapedByte` and `UnpackDomainName`.
I know I just landed #845, but I didn't realise just what an improvement could be had. `strconv.AppendInt` has a table-lookup optimisation for numbers `< 100`, which is all `UnpackDomainNameLongestUnprintable` has, so for names that have unprintable octets `> 126` this should be an even greater performance improvement.
These benchmarks were taken after #844 and show a very big improvement (memory is the same):
```
name                                   old time/op    new time/op    delta
UnpackDomainName-12                       125ns ± 5%     126ns ± 7%     ~ …
```
> Use a table lookup for escaping unprintable bytes

- msg_generate.go
- msg_helpers.go
- zmsg.go
This PR makes `packDataDomainNames` more consistent with `PackDomainName` where it will only be called with `compress = true` for <code>\`dns:"cdomain-name"\`</code>. This change is purely cosmetic.
> Move compress=false out of packDataDomainNames into caller

- dns_bench_test.go
- length_test.go
- msg.go
*Performance hit incoming.*
`Len` will now take escaping into account and return the correct length regardless of escaping.
These are the benchmarks:
```
name                       old time/op    new time/op    delta
MsgLength-12                  349ns ± 4%     387ns ± 2%   +10.92%  (p=0.000 n=9+9)
MsgLengthNoCompression-12    28.0ns ± 1%    63.3ns ± 2%  +125.91%  (p=0.000 n=10+10)
MsgLengthPack-12             1.10µs ± 8%    1.12µs ± 4%      ~     (p=0.138 n=10+10)
MsgLengthMassive-12          26.1µs ± 2%    27.3µs ± 6%    +4.85%  (p=0.000 n=9+10)
MsgLengthOnlyQuestion-12     10.0ns ± 3%    17.1ns ± 2%   +72.14%  (p=0.000 n=10+9)
MsgLengthEscapedName-12      9.25ns ± 1%   96.08ns ± 1%  +938.58%  (p=0.000 n=9+10)
PackMsg-12                    957ns ± 1%    1015ns ± 1%    +6.10%  (p=0.000 …
```
> Fix compressed length calculations for escaped names

- types.go
- zmsg.go
- ztypes.go
Although [RFC 1183](https://tools.ietf.org/html/rfc1183#section-3.3) allows names in the RT record to be compressed with:
```
The concrete encoding is identical to the MX RR.
```
But [RFC 3597](https://tools.ietf.org/html/rfc3597#section-4) specifically prohibits compressing names in any record not defined in [RFC 1035](https://tools.ietf.org/html/rfc1035#section-3.2).
**Note:** I had to modify the two generated files by hand as they weren't picking up my changes to types.go for some reason. There shouldn't be any changes running `go generate` later though.
Updates #522
> Stop compressing names in RT records

- length_test.go
- msg_test.go
As I'm working on the compression code and I trip either of these tests I keep being hit with a massive wall of incomprehensible text that tells me nothing about what's gone wrong. These maps end up with nearly a thousand different entries.
This PR adds a helper function that formats the maps in a much nicer way and greatly simplifies debugging test failures.
> Pretty print test compression map differences

- types.go
Just put add ";" in front of it, instead of the whole pseudo option
text.
Fixes #855
> Simplify TKEY presentation format

- msg_generate.go
- msg_helpers.go
- parse_test.go
- types.go
- types_generate.go
- zduplicate.go
- zmsg.go
- ztypes.go
Sorely missing from this library. Add it.
> Add NULL record

- edns.go
This now matches EDNS0_EXPIRE.unpack.
> Use binary.BigEndian.PutUint32 in EDNS0_EXPIRE.pack

- privaterr.go
- scan.go
- scan_rr.go
This changes how comments are handled by the scanning code. They're now handled solely by `zlexer` and `ZoneParser`. Now comments no longer infest scan_rr.go in sometimes odd ways. There should be no observable behaviour changes.
> Move scanner comment handling out of scanRR

- types.go
- zduplicate.go
- zmsg.go
- ztypes.go
The NULL record has yet to make it into an actual release and I'd like to propose renaming the `Anything` field to `Data`. I think `Data` is clearer than `Anything` about what the actual contents of the RR is.
I know RFC 1035 describes the NULL record as:
```
3.3.10. NULL RDATA format (EXPERIMENTAL)
+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
/                  <anything>                   /
/                                               /
+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
Anything at all may be in the RDATA field so long as it is 65535 octets
or less.
```
but I don't think naming it `Anything` is clearer. See for example the definition of the NS record and how the field is named (note the lack of angled brackets):
```
3.3.11. NS RDATA format …
```
> Rename NULL's Anything field to Data

- duplicate_generate.go
- zduplicate.go
This is clearer, faster and more correct. The packing code for A records will convert IPv4-in-v6 address to IPv4 address which wasn't handled by the previous code, but is handled by `(net.IP).Equal`.
> Use (net.IP).Equal in isDuplicate functions

- dns.go
- msg.go
- msg_generate.go
- privaterr.go
- zmsg.go
This eliminates the `typeToUnpack` map which should offer a small speedup to program init time. This also notably simplifies the code.
> Use an interface method for unpacking records

- README.md
Add RFC 8499 on DNS terminology. This is and will be used to name
various things in this package.
> Add newly released RFC to readme

- defaults.go
- labels_test.go
- msg.go
- msg_generate.go
- msg_helpers.go
- zmsg.go
I'm not sure if this is worth doing, but @miekg mentioned it in https://github.com/miekg/dns/pull/818#issuecomment-442355376. `IsDomainName` is documented as being incredibly liberal, so it may be possible to make it simpler at the expense of strictness.
> Stop using packDomainName in IsDomainName

- dns.go
- msg.go
- msg_generate.go
- msg_helpers.go
- privaterr.go
- zmsg.go
The header will be packed into the `msg` buffer before the generated `pack()` function is called. This simplifies the generated code and eliminates the `headerEnd` return value.
> Move RR header packing out of generated code

- server.go
As defaultReader contains a single pointer, we can pass it by value and avoid an allocation when it's put inside an interface{}.
> Use a value reciever for defaultReader

- dnssec.go
- sanitize.go
- sig0.go
- update.go
Header is an interface method so there's non-zero overhead when calling it. This should be ever so slightly faster.
> Avoid calling RR.Header more than once per RR

- defaults.go
- labels.go
- msg.go
- scan.go
This is more consistent throughout the library.
> Use IsFqdn and Fqdn helper functions more

- xfr.go
I'm not sure how this ended up like it did, but it was obviously unintentional.
While I'm here, return an error for unknown question types. Previously this would just be silently ignored leaving nothing to close the returned channel or return an error.
> Flatten goroutine inside goroutine in Transfer.In

- defaults.go
- msg.go
- sig0.go
This is cosmetic but makes the code clearer. There weren't many instances where the length had been hardcoded.
> Use headerSize const instead of hardcoded 12

- client.go
- labels.go
- msg.go
- privaterr.go
- server.go
- smimea.go
- tlsa.go
- tsig.go
- udp_windows.go
- xfr.go
This is cosmetic but makes the library a little simpler and more uniform.
> Simplify and unify various returns

- client.go
- dnssec.go
- edns.go
- msg_helpers.go
- scan.go
- scan_rr.go
- tsig.go
- tsig_test.go
- xfr.go
These were all caught with [gogrep](https://github.com/mvdan/gogrep) using a query like the following for each type:
```
gogrep -x '[]byte($x)' -x '$x' -a 'type([]byte)'
```
> Remove pointless casts

- dns.go
- edns.go
- parse_test.go
- privaterr.go
- scan.go
- scan_rr.go
- tsig.go
- types.go
This is #884 but for zone file parsing.
This eliminates the `typeToparserFunc` map which should offer a small speedup to program init time. This also simplifies the code.
> Use an interface method for parsing zone file records

- dns.go
- duplicate.go
- duplicate_generate.go
- duplicate_test.go
- edns.go
- privaterr.go
- zduplicate.go
This is simpler and more inline with other RR methods and eliminates the `isDuplicateRdata` switch statement. This also eliminates a panic that could occur if a record was lying about it's RRType (see `TestDuplicateWrongRrtype`).
> Use an interface method for IsDuplicate

- acceptfunc.go
- acceptfunc_test.go
The answer section of a notify can contain a SOA record that we should
not ignore in the DefaultAcceptFunc.
> RFC 1996 allows SOA in answer in notify

- dns_test.go
- edns.go
- types_generate.go
- ztypes.go
While debugging CoreDNS, I found that the dns.Msg.Copy() was partially invalid for OPT records.
Because OPT is []EDNS0 and EDNS0 is an interface (a pointer...).
- Added a Copy() method on the EDNS0 interface
- modify the generation of OPT.Copy() (file types_generated)
- add a UT in Msg that show failing before the change and correct after (although testing only EDNS0_LOCAL sub type).
> fix OPT Record deep copy 

- client.go
As per this article: https://rakyll.org/deprecated/. Also, IDEs like GoLand and VSCode pick up on this format and render a strikethrough of deprecated methods in their editors.
> follow convention for deprecation notice in ExchangeConn

- types.go
- types_test.go
This fixes the `String` formatting of RP records. The use of `sprintName` is consistent with other `String` functions in `types.go`.
Fixes #913 
/cc @paulf69487623
> Fix String formatting of RP record

- .travis.yml
This adds the newly released go1.12 to the Travis build.
Do we still intend to support go1.10 or would you like that removed @miekg?
> Add go1.12 to Travis CI

- dnssec_keyscan.go
When migrating zones to CoreDNS, it did not accept private key files
the former bind setup gracefully accepted. It turned out they had a
trailing newline for whateveer reason. The dns library should handle
them gracefully, too.
> Ignore empty lines when parsing private keys

- README.md
goresolver is a DNSSEC validating resolver library based on miekg/dns
> Added github.com/peterzen/goresolver

- server.go
the description states
// By default DefaultMsgAcceptFunc will be used.
but actually defaultMsgAcceptFunc (not visible outside of the package) was used.
At least the description and code should be consistent.  The proposed change assumes the description is correct.
> corrected default value of Server.MsgAcceptFunc as documented

- dns_bench_test.go
- scan_rr.go
- scan_test.go
And vice versa for IPv4 with AAAA.
The implementation of isIPv6 is inspired by https://github.com/golang/go/blob/e341bae08d75611adea6566c1d01c1e3a0de57f9/src/net/ip.go#L678-L681 .
> ZoneParser: error on parsing an IPv6 address in an A record

- server.go
This was changed in #808, but I missed this function. Apparently no one noticed, I'm not sure how this hasn't been caught :man_shrugging:.
> Correct Close() check in Server.serve

- server.go
This restores the pre-worker method split of `Server.serveTCPConn` and `Server.serveUDPPacket`. This also removes the `msg` field from the `response` struct. It also reduces some duplication in `Server.serveDNS`.
Closes #930
> Split Server.serve into separate TCP and UDP methods

- client.go
- server.go
The previous code is quite complicated and has some very subtle error behaviour, while this new code is far simpler and more obvious while behaving very similarly.
While there are a select number of subtle changes in error behaviour, I don't believe it will be noticeable in normal use or that anyone would be relying on it. It ultimately wasn't particularly helpful.
It's very late here and this code was quite complicated, so it may be worth running the CoreDNS tests against this PR (which also includes the TCP writing changes from master) before merging.
> Simplify TCP reading

- dnssec.go
- dnssec_keyscan.go
- dnssec_privkey.go
- sig0.go
This is more idiomatic and has less overhead. Also along for the ride is making the `big.NewInt(1)` in `DNSKEY.PrivateKeyString` a global variable.
> Use new(big.Int) instead of big.NewInt(0)

- client.go
This was accidentally added in #935, though I'm not quite sure why I ended up with this cast.
> Remove pointless cast in Conn.Read

- clientconfig.go
- dnssec.go
- edns.go
- labels.go
- msg.go
- msg_helpers.go
- types.go
This replaces the use of manual `for i := 0; i < len(...); i++` loops with simpler and more idiomatic `for range` loops.
`Msg.CopyTo` had a slight reorganisation of it's logic which leaves it much simpler: 5bab01b0a655730908f4523a5b2510d80a515167.
> Use for range loops instead of manual for loops

- msg_helpers.go
- msg_test.go
- types_generate.go
- ztypes.go
The `packDataA` and `packDataAAAA` functions don't pack anything for dynamic updates (when `len(a) == 0`), but this wasn't previously considered for the `Len` code. This also fixes the overflow check inside the `packData*` functions that would fail with the now smaller buffer.
> Fix Len(rr) for dynamic update for A/AAAA/L32 RRs

- client.go
Previously it was possible for two different questions to hit the same single in flight entry if the type or class isn't in the relevant `XToString` map. This could happen for a proxy server or similar.
> Change the single in flight key for Client.Exchange

- server.go
There was a missing case (`MsgIgnore`) where the buffer wasn't returned to the `sync.Pool`.
Thanks to @jrajahalme for spotting this.
Closes #954
> Always return UDP buffers to pool

- types_generate.go
- ztypes.go
`dns:"hex"` fields are not packed with any extra trailing byte. This was causing a mismatch between `PackRR` and `Len`.
> Fix dns:"hex" field len being off-by-one

- privaterr.go
This code has bugged me for a while, but I couldn't find a clean way to eliminate it until now.
This eliminates `mkPrivateRR` and reduces the risk of panic.
> Simplify PrivateRR copying

- msg_truncate.go
The function is called Truncate, not Scrub (that was the old name).
Updated the function's documentation to rename this.
> Remove the word Scrub

- xfr.go
- xfr_test.go
Requests sent via `Transfer.Out()` do not currently check if the request has TSIG record, so those responses are sent without expected TSIG record(s).  This follows the pattern described in the documentation and adds a check to `q *Msg` for a TSIG record and, if present, sets the TSIG on the outgoing message(s).
> Set TSIG on Transfer Out

- fuzz_test.go
- msg_helpers.go
An option needs a minimum of 4 bytes that contains OPTION-CODE and OPTION-LENGTH
The code was checkign off + 3 > len(msg) instead of off + 4
> packDataOpt: fix overflow in packing opt

- README.md
- dnssec.go
- dnssec_keygen.go
- dnssec_keyscan.go
This removes RSAMD5 as an algorithm you can use. BIND also has
deprecated *all* DSA algos which is more involved can removes more
helper codes as well, so that should be done in a new PR.
This adds a ErrDeprecated signalling the DNSSEC algorithm is removed and
can't be used.
See #968
> DNSSEC: remove deprecated algorithm RSAMD5 (RFC 6944)

- dnssec.go
- dnssec_keygen.go
- dnssec_keyscan.go
- parse_test.go
This follows BIND9 and removed support for the DSA family of algorithms.
Any DNSSEC implementation should consider those zones using it,
insecure.
> Remove DSA* algorithms

- fuzz_test.go
- msg_helpers.go
- types.go
Both NSEC and NSEC3 use the same logic to pack the bitmap.
CSYNC.pack also appear to make use of `packDataNsec` so I am giving it
the same treatment by moving the logic in a helper function and making
all those types `len` call use that function.
> [nsec3] fix crash in nsec3 packing

- client.go
This change allows alternative net.Conn implementations such as in memory connections based on net.Pipe for implementation testing.
> Handle all net.Conn connections correctly

- acceptfunc.go
- server.go
- server_test.go
Context in issue #975.
cc @chantra
> ignore Z flag in queries, clear Z flag in automatic replies

- dns.go
- edns.go
- privaterr.go
- scan.go
- scan_rr.go
- scan_test.go
- tsig.go
- types.go
This also includes several simplifications to the parsing code.
Another approach that doesn't need to add the `Peek` method is to pass the first `lex` token directly to the `parse` method like: `parse(c *zlexer, l lex, origin string) *ParseError`. That may be simpler and preferred, but it doesn't otherwise add much.
There is one `TODO` in this PR, previously `slurpRemainder` was only called for some RR types on  dynamic updates. I'm not sure if this is actually observable or not though.
This may still need some polish, but it's here for review at least.
Fixes #901
> Prohibit newlines before record data in the ZoneParser

- acceptfunc.go
- server.go
- server_test.go
One of the test from DNS Compliance testing validates that if the opcode
is not supported, a NOTIMPL rcode is returned.
https://gitlab.isc.org/isc-projects/DNS-Compliance-Testing/blob/e0884144dde6704128e22acc14e2b65ba41a92b2/genreport.c#L293
This diff makes the default acceptfunc support this case and reply with
NOTIMPL instead of FORMERR.
> Reply with NOTIMPL when Opcode is not supported

- msg_truncate.go
- msg_truncate_test.go
This changes the `(*Msg).Truncate` implementation to set the `TC` header flag whenever any RR is omitted from the response. Previously the `TC` flag was only set when an answer RR had to be omitted.
Fixes #987 (see this issue for a discussion on this approach).
/cc @markdingo
> Set the TC bit more aggressively in Truncate

- labels.go
- labels_test.go
This commit changes the labels functions to step through labels section-by-section instead of splitting them and thus allocating a slice.
Where possible allocations are reduced to 0.
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkSplitLabels-12           41.4          34.9          -15.70%
BenchmarkLenLabels-12             25.8          15.5          -39.92%
BenchmarkCompareDomainName-12     107           39.3          -63.27%
BenchmarkIsSubDomain-12           348           120           -65.52%
benchmark                         old allocs     new allocs     delta
BenchmarkSplitLabels-12           1              1              +0.00%
BenchmarkLenLabels-12             0              0              +0.00%
BenchmarkCompareDomainName-12     2              0 …
```
> labels: eliminate most allocations and improve perf by 15-65%

- serve_mux.go
This has been a long standing TODO. [golang.org/cl/137575](https://golang.org/cl/137575) was included in go1.12 which is the oldest officially supported release.
> Use strings.ToLower in ServeMux.match

- msg_helpers.go
- msg_helpers_test.go
This is an alternative approach to #1009.
I'm not convinced this is really worth doing, because it does add a decent amount of complexity no matter how you approach it. That being said, it does show a performance improvement and reduces the allocations when there is escaping.
```
name                       old time/op    new time/op    delta
UnpackString/Escaped-12      83.7ns ± 7%    78.2ns ± 3%   -6.50%  (p=0.000 n=10+9)
UnpackString/Unescaped-12    57.8ns ± 9%    50.4ns ±13%  -12.74%  (p=0.000 n=10+10)
name                       old alloc/op   new alloc/op   delta
UnpackString/Escaped-12       48.0B ± 0%     32.0B ± 0%  -33.33%  (p=0.000 n=10+10)
UnpackString/Unescaped-12     32.0B ± 0%     32.0B ± 0%     ~     (all equal)
name                       old allocs/op  new allocs/op  delta …
```
> Improve unpackString performance

- msg.go
- msg_truncate.go
This improves runtime by 20-40% and more importantly significantly reduces memory usage and allocations.  The goal here is to reduce allocations.
Benchmarks:
```
benchmark                                          old ns/op     new ns/op     delta
BenchmarkMsgLength-12                              337           263           -21.96%
BenchmarkMsgLengthNoCompression-12                 48.0          49.6          +3.33%
BenchmarkMsgLengthPack-12                          1010          963           -4.65%
BenchmarkMsgLengthMassive-12                       25409         14551         -42.73%
BenchmarkMsgLengthOnlyQuestion-12                  13.3          13.6          +2.26%
BenchmarkMsgLengthEscapedName-12                   108           112           +3.70%
BenchmarkPackDomainName-12 …
```
> pool the transient maps used for Msg Pack, Truncate and Len

- types.go
- types_test.go
This PR improves performance and memory usage by lazily allocating the `strings.Builder` and by inlining the `writeDomainNameByte()` logic.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkSprintName-12              180           120           -33.33%
BenchmarkSprintName_NoEscape-12     198           82.4          -58.38%
benchmark                           old allocs     new allocs     delta
BenchmarkSprintName-12              2              1              -50.00%
BenchmarkSprintName_NoEscape-12     1              0              -100.00%
benchmark                           old bytes     new bytes     delta
BenchmarkSprintName-12              48            32            -33.33%
BenchmarkSprintName_NoEscape-12     32            0             -100.00%
``` …
> types: improve the performance of sprintName by ~30% and halve allocs

- msg.go
- msg_truncate.go
This reverts #1006, see discussion on the PR. Def. worth exploring this
furhter and pushing a more correct approach.
This reverts commit 9578caeab0b302ad470aacae5613d2d0c85530ac.
> Revert "pool the transient maps used for Msg Pack, Truncate and Len (#1006)"

- generate.go
- generate_test.go
Running the fuzzer on NewRR, some crashes came up that could be
prevented by checking that the token after the range is a Blank.
This diff checks that and return an error when the blank is not found.
> [fuzz] Fix crashes when parsing GENERATE

- generate.go
- generate_test.go
- scan.go
> Limit $GENERATE range to 65535 steps

- labels.go
- labels_test.go
This reverts commit ab6ac402ba8b77a932131197c2c9b49609423771.
This break CoreDNS tests and probably a lot of other apps as well.
Reverted.
Fixes #1021
> Revert "labels: eliminate most allocations and improve perf by 15-65% (#1007)"

- fuzz.go
Fixes #1025
```
GO111MODULE=off make -f Makefile.fuzz build
go-fuzz -bin=dns-fuzz.zip -workdir=fuzz -func Fuzz
GO111MODULE=off make -f Makefile.fuzz build-rr
go-fuzz -bin=dns-fuzz.zip -workdir=fuzz -func FuzzNewRR
```
> [fuzzer] Avoid fuzzing parser with line that contains "$INCLUDE"

- edns.go
- edns_test.go
This is a breaking change as it adds a new field to `EDNS0_UL`. I'd guess there's little to no usage of this option in the wild so it probably won't impact anyone.
The new format is described in https://tools.ietf.org/html/draft-sekar-dns-ul-02#section-4.
Fixes #869.
> Update EDNS0_UL to draft-sekar-dns-ul-02

- .travis.yml
- fuzz_test.go
Use a better name in the fuzzing test to not spam the travis output,
move to Go 1.13.x in travis.yaml
> build: reduce testing output

- generate.go
- generate_test.go
- scan.go
While the range number of GENERATE is now limited, one can pass
a line with 2 $GENERATE directive that will exponentially increase the
time spent generating RRs.
Limit to only one per line.
Fixes #1020
> [zone parser] disallow nested $GENERATE directive

- labels.go
- labels_test.go
NextLabel and PrevLabel are heavily used in the "file" plugin in coredns. This change introduces benchmark tests and improves the performance (on my machine).
It eliminates all allocations and uses strings in a way that should make L1-Cache-Hits more likely.
The time for coredns "file"-plugin Requests is cut roughly in half.
> Speed up NextLabel and PrevLabel

- edns.go
- edns_test.go
- msg_helpers.go
- ztypes.go
Replace all the private methods in the EDNS0 with public methods.
Additionally, as suggested in issue #857, made Pack receive a
pre-allocated byte array, introduce a Len method, and have Pack
and Unpack return the number of octets written and read (respectively)
if there was no error.
Closes #857
> Export EDNS0 interface

- msg.go
Notably, if crypto/rand returns an error this will silently fall back to math/rand, since
the exported signature can't return an error.
Fixes #1043 and #1037
> Use crypto/rand for random id generation.

- tsig.go
TSIG doesn't have a presentation format, when converting to a string
prefix the record with a semi-colon so it will be parsed as a comment.
> Add ; before printing TSIG

- LICENSE
This license file is not being recognized by Github, nor by the new
google golang thingy recently launched. Don't remove those lines just
yet, but put them at the bottom
> Put added license bit at the bottom

- .travis.yml
- duplicate_generate.go
- go.mod
- go.sum
- msg_generate.go
- types_generate.go
The programs to generate type definitions use `go/importer` which is not compatible with go modules and require `miekg/dns` to be installed globally. This PR replaces `go/importer` with the new `golang.org/x/tools/go/packages` which is module aware.
> code generation compatible with go modules

- msg.go
- msg_truncate.go
Signed-off-by: Lehner Florian <dev@der-flo.net>
This is a tiny code clean up. In both cases, a value is assigned to the local variable `l` but never used afterwards.
> unused local variable assignment 

- parse_test.go
- scan_rr.go
https://github.com/miekg/dns/issues/1083
Fixing default values for HorizPre and VertPre fields at LOC record
According to RFC-1876 those fields should be:
"a pair of four-bit unsigned
integers, each ranging from zero to nine, with the most
significant four bits representing the base and the second
number representing the power of ten by which to multiply
the base.  This allows sizes from 0e0 (<1cm) to 9e9
(90,000km) to be expressed"
Current values for HorizPre and VertPre (165=0xA5 and 162=0xA2)
are incorrect because the first HEX digit is greater then 9
The default values should be:
HorizPre = 10000m = 10000 * 100 cm = 10^6 = 0x16
VertPre  = 10m    = 10 * 100 cm    = 10^3 = 0x13
Size     = 1m     = 1 * 100 cm     = 10^2 = 0x12
The value of Size was correct, but this PR changes it to HEX …
> correct default values fields in LOC record

- scan_rr.go
Use "err" if we are in a if-clause, if not start with e and then e1, e2,
etc. If this is be sure to never run into the situation where the error
interface has been given a type and thus can never be compared with nil
again: https://golang.org/doc/faq#nil_error
Something more elegant might be needed in the long run. There is also a
vague plan to autogenerate this - problem there is the weirdness some
RRs for parsing (depending on previous values, etc. etc.) Not that would
solve this issue, but does stop people from having to edit this code
directly ever again.
> Fix all cases of error handling

- defaults.go
- dnssec.go
- labels_test.go
- serve_mux.go
- tsig.go
This PR adds `Canonical` function which returns given domain in canonical form.
I realise the implementation is rather trivial. There are a few places the library where a name in canonical form is required (e.g. map with TSIG keys) but canonical names are also useful to normalize names in other context. Essentially all projects and little tools that I've ever worked on and that use this library have a copy of this little function. Therefore I think it might be worth including in the library even though the implementation is trivial.
Please, let me know what you think.
Also, let me know if `Canonical` is name or if it should be something else like `CanonicalName`.
> CanonicalName function to return domain name in canonical form

- types.go
Paraphrase @miekg's response to emphasize that multiple questions in the question section of a DNS message is not supported in practice.
refs miekg/dns#1092
> RFCs allow multiple questions, but not in practice

- .github/workflows/cifuzz.yml
- .github/workflows/go.yml
The basic idea is to run `go test` for each pull request.
Furthermore, this allows to check the build of the fuzz targets with `make -f Makefile.fuzz`, and running of the oss-fuzz fuzzer with CIFuzz cf https://google.github.io/oss-fuzz/getting-started/continuous-integration/
You can test this (once it is merged) with a dummy Pull Request with for instance
```
diff --git a/scan.go b/scan.go
index e52f43c9..44140db4 100644
--- a/scan.go
+++ b/scan.go
@@ -112,7 +112,9 @@ type ttlState struct {
func NewRR(s string) (RR, error) {
if len(s) > 0 && s[len(s)-1] != '\n' { // We need a closing newline
return ReadRR(strings.NewReader(s+"\n"), "")
-       }
+} else if len(s) == 7 {
+panic("test cifuzz")
+}
return ReadRR(strings.NewReader(s), "")
}
```
> Continuous integration with GitHub workflow

- scan_rr.go
Found by oss-fuzz
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21892
The optimization comes from 
https://hermanschaaf.com/efficient-string-concatenation-in-go/
My benchmark on the oss-fuzz test case is from 80 seconds to 0.1 second with this PR
Reproducer program is
```
package main
import (
"fmt"
"io/ioutil"
"os"
"runtime/pprof"
"github.com/miekg/dns"
)
func main() {
f, err := os.Create("cpu.prof")
if err != nil {
fmt.Printf("error %#+v\n", err)
return
}
_ = pprof.StartCPUProfile(f)
data, err := ioutil.ReadFile(os.Args[1])
if err != nil {
fmt.Printf("Failed to read corpus file", err)
}
fmt.Printf("Starting %s\n", os.Args[1])
dns.NewRR(string(data))
fmt.Printf("Finished\n")
pprof.StopCPUProfile()
f, err = os.Create("heap.prof")
if err != nil {
fmt.Printf("error %#+v\n", err) …
```
> Efficient string concatenation

- generate_test.go
- parse_test.go
- privaterr_test.go
- scan.go
- scan_test.go
This removes `ParseZone()` and `parseZone()` as pointed by @miekg in #1059
> refactor: remove ParseZone and parseZone

- client.go
- client_test.go
#614 requested that connection reuse be implemented in this library to help improve performance when using TCP/TCP-TLS connections.  This was rejected, fairly, because of the complexity in handling that logic within the library.  This PR would solve the problem without introducing connection management code into the library at all.  Instead it does some minor refactoring in order to expose the ability for the *caller* to manage connections and pass them in to the library via the ExchangeWithConn function.  The existing Exchange behavior is preserved, so backwards compatibility shouldn't be an issue.
> Adds function ExchangeWithConn

- duplicate_generate.go
- zduplicate.go
isDuplicate has been always returning false before I applied this patch for derived types.
Test:
```go
e := new(DNSKEY)
fmt.Println(e.isDuplicate(e))
f := new(CDNSKEY)
fmt.Println(f.isDuplicate(f))
fmt.Println(e.isDuplicate(f))
```
Before:
```
true
false
false
```
After:
```
true
true
false
```
> Generate isDuplicate for derivatives

- types.go
- types_test.go
* Properly escape quotes and backslashes for sprintTxtOctet
* Re-arrange expected/got messages in tests
Sorry for the PR spam earlier, i rebased on my master and got confused by issue referencing. It should be referencing #1101
> Fix URI and CAA parsing on quotes and backslashes. (#1101)

- msg_test.go
this is being deprecated in newer Go version and used here for no good
reason, move string(64) to the character is needs to represent and
otherwise use the work around (converting to rune) the Go devs propose.
In general this UnpackTest could actually do without all this tossing
about.
> Remove string(n)

- types_generate.go
- ztypes.go
Fixes:
```go
e := new(DNSKEY)
f := new(CDNSKEY)
fmt.Println(e.isDuplicate(e))        // true (correct)
fmt.Println(e.isDuplicate(e.copy())) // true (correct)
fmt.Println(f.isDuplicate(f))        // true (correct)
fmt.Println(f.isDuplicate(f.copy())) // false
```
**Edited** to address tmthrgd's comment
`isDuplicate` is actually working, `copy` is broken. Here's why `copy` is broken:
When I do
```go
f := new(CDNSKEY)
g := f.copy()
```
since `CDNSKEY` is a derived type, it doesn't (didn't) have its own `copy` method. So DNSKEY's copy method was called:
```go
func (rr *DNSKEY) copy() RR {
return &DNSKEY{rr.Hdr, rr.Flags, rr.Protocol, rr.Algorithm, rr.PublicKey}
}
```
which clones CDNSKEY's internal DNSKEY and returns it as a DNSKEY. How I solved it was a wrapper that casts the result of the …
> Generate copy() for derived types

- tsig.go
- tsig_test.go
The current implementation of `TsigVerify` is compliant to RFC2845 in that it first checks 'time signed' and then verifies the signature.  But this logic is known to have a security vulnerability as reported in CVE-2017-3142/3143.
The protocol is being revised as draft-ietf-dnsop-rfc2845bis, reversing the order of these checks.  This PR implements the new behavior in a straightforward way.  While the new protocol spec is still an internet draft, it's already in the RFC editor queue, so I believe it's mature enough.
(Added test covers this specific case with some other error conditions from `TsigVerify`)
> make TsigVerify check time after signature per rfc2845bis

- tsig.go
- tsig_test.go
Currently, `tsigBuffer` ignores any error from `packXXX` functions, so `TsigGenerate` or `TsigVerify` can't notice that condition.  but since the buffer used for those `packXXX` only has `DefaultMsgSize` (4096) bytes, and "other data" can be up to 64KB, an arbitrary sender of TSIG message can cause this error in `TsigVerify`.  In practice it would just result in failing to verify the signature, but I think it's cleaner and safer to catch this kind (i.e., "overflow") of error conditions explicitly.
This PR does just that (also catching other minor errors).
> catch error from tsigBuffer, mainly to detect other data overflow

- tsig.go
- tsig_test.go
The current implementation of `TsigGenerate` ignores the TSIG error and other data fields of the TSIG RR in the passed DNS message for generating the signed binary-format message (it uses these fields correctly for computing the MAC).  So the resulting message would fail to be verified at the recipient.  This PR is a straightforward fix to this problem.
> fix TsigGenerate for non-0 TSIG error or non-empty other data

- tsig.go
- tsig_test.go
This PR is a trivial implementation of supporting HMAC SHA224 and HMAC SHA384 for TSIG.
While these algorithms are "optional" per RFC4635, they are supported in other implementations such as BIND, so supporting them would be nice for better interoperability (and the implementation is trivial).
> add support for HMAC SHA224 and 384 TSIG algorithms

- scan_rr.go
As in the title, instead of having a "TODO" to check for value being too high, just parse it properly and allow the `strconv.ParseUint` to return a too big value error.
PS: Please check that the resulting code works properly, I have not compiled this or/and run tests (assuming this  code is tested).
> Fix a "TODO error out on > MAX_UINT32"

- parse_test.go
- scan.go
- scan_rr.go
The current implementation of LOC RR's (text) parser doesn't perform range check on the latitude and longitude fields, so it can allow values out of the range specified by RFC1876:
```
d1:     [0 .. 90]            (degrees latitude)
d2:     [0 .. 180]           (degrees longitude)
m1, m2: [0 .. 59]            (minutes latitude/longitude)
s1, s2: [0 .. 59.999]        (seconds latitude/longitude)
```
This PR makes sure that a textual LOC RDATA unexpectedly contains out of range latutide or longitude values.  Note also that it's possible that the resulting 32-bit encoded value is out of range even if degrees, minutes and seconds in the textual representation are all in range.  This PR prevents this type of out-of-range value, too.  These validations help improve interoperability there's a …
> validate LOC's lat/long field values not to be out of range

- parse_test.go
- scan.go
`stringToCm`, a subroutine for `LOC.parse`, has a couple of issues that violate RFC1876:
- there's an off-by-one error in calculating the base and exponent values: a value of 100 should be encoded as 0x12 (1e2) but this implementation encodes it as 0xa1 (10e1).  (btw #1084 fixed the same problem but only for the default value)
- the current implementation treats "0.1m" as "1cm" (0x01 in the encoded form) as it simply extracts the number and passes it to `Atoi`.  But the actual value is 10cm and should be encoded as 0x11.
- the current implementation accepts a negative value
This PR fixes these issues.
It also introduces some other enhancements that are not necessarily for standard conformance:
- It enforces the max value (90000000.00m) described in the RFC more strictly.
- It allows …
> fix and enhance stringToCm to parse LOC RR optional fields

- msg_helpers.go
- msg_helpers_test.go
The current implementation of `APL.pack` violates the following part of RFC3123 (Sections 4.1 and 4.2):
> the sender MUST NOT include trailing zero octets in the AFDPART regardless of the value of PREFIX
This PR implements a trivial fix to this violation.
> make sure removing trailing zero octets in APL AFDPART

- serve_mux.go
- server.go
... instead of RcodeServerFailure.
> answer queries with no matching handler with RcodeRefused

- client.go
It looks like an early revision of #511 deprecated this function, but during
review it was un-deprecated, and this comment was never cleaned up.
> Remove comment saying ExchangeContext is deprecated.

- README.md
These domain either nxdomain/404 or just generic sites selling some
service.
Remove them from the readme.
> readme: remove too generic users

- client.go
While Client.UDPSize is honored when using Client.Exchange(), the value is currently not passed on to any Conn that is created with Client.Dial(). For consistency, I believe the Conn should inherit the value from the Client.
> Set UDPSize in connections created with client.Dial()

- .github/workflows/go.yml
- .travis.yml
This bumps Travis CI to the last two supported golang releases, as documented in the readme: go1.14 and go1.15.
It also bumps the GitHub Code Action CI to go1.14 as it doesn't yet supported go1.15 (see actions/setup-go#74).
This is blocking #1155.
> Bump CI tested go versions

- msg_truncate.go
Retain TC bit if original message was already marked truncated.
Fixes coredns/coredns#4183
This could alternately be fixed in coredns/coredns, although I can't think how reverting the TC bit would be desirable in any scenario, hence suggesting the fix upstream here.
Signed-off-by: Chris O'Haver <cohaver@infoblox.com>
> Retain TC bit if original message was already marked truncated

- msg_truncate.go
Follow up after #1171, update the docs about TC and use the MinMsgSize
constant for 512 in the code.
> Update doc for Truncate

- length_test.go
Original PR doesn't make clear why this is 900-now assuming we want to
cross the 14 bit length boundary.
Up to 900 creates a super large (>2^16) message. Not sure why that needs
testing.
Also remove the packs at lower sizes.
> Make the 900 number lower in this test

- svcb.go
The SVBC record didn't have a class, so add that and use struct literal
to put it all on 1 one. Use `s` for SVCB records, and `h` for HTTPS to
be more consistent.
> svcb: doc updates

- client.go
- client_test.go
- server_test.go
This fixes the following problem:
At time 0, we send a query with ID X from port P.
At time T, we time out the query due to lack of response, and then send a different query with ID Y.  By coincidence, the new query is sent from the same port number P (since port numbers are only 16 bits, this can happen with non-negligible probability when making queries at a high rate).
At time T+epsilon, we receive a response to the original query. Since the ID in this response is X, not Y, `exchange` returns `ErrId`, preventing the second query from succeeding.
Since UDP does not have connections, there's no guarantee that a response that we receive is actually associated with the query that we sent - the ID is needed to make the association. Therefore, it's more appropriate to ignore replies with …
> Ignore responses with unexpected IDs

- svcb.go
`&dns.HTTPS{Hdr: ...}` fails due to `cannot use promoted field SVCB.Hdr
in struct literal of type dns.HTTPS`. Fix this, less readable
alternatives include using `dns.SVCB` directly, or `&dns.HTTPS{SVCB:
dns.SVCB{Hdr: ...}}`.
Fix the draft reference, draft-02 has not been published yet. Fix ECH,
its type has changed from base64 to a byte array.
> svcb: documentation fixes

- dnssec.go
- dnssec_keygen.go
- dnssec_keyscan.go
- dnssec_privkey.go
- doc.go
- sig0.go
crypto/dsa is formally deprecated as of go1.16 and DSA support was largely removed from this library in 9c315c51c341 (#972), but some remnants remained.
> Remove the remnants of DSA support

- dnssec.go
AFAIK, the only way to get an RSAMD5 DNSKEY was to manually construct one. This is ancient, just get rid of it.
The only remaining usage of md5 is in tsig.go. Hopefully that might be removable as well.
> Remove RSAMD5 support from (*RRSIG).Verify

- server_test.go
- tsig.go
- tsig_test.go
The [Wikipedia article for TSIG](https://en.wikipedia.org/wiki/TSIG#Alternatives_to_TSIG) claims that HMAC-MD5 is "still in common usage", but doesn't provide any source for this. If there's no one who desperately needs this, I'd like to remove it entirely.
MD5 is a severely broken algorithm so it would be great to get it out of this library, even removing legacy support.
Considering that the TSIG algorithm is set by the TSIG record and not by the secret key (!! see [the JWT token mess](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)), an exploitable weakness in HMAC-MD5 could allow easy forging of TSIG records even on systems that do not otherwise use MD5.
> Remove HMAC-MD5 support from TSIG

- xfr_test.go
`axfrTestingSuite` returned the test function that was never actually executed. These were broken from the beginning in #939 awkwardly, though the test cases pass fine once fixed.
Updates #939
> Fix XFR tests

- acceptfunc_test.go
- client_test.go
- server.go
- server_test.go
- xfr_test.go
This commit adds support for listening on generic net.PacketConn's for UDP DNS requests, previously *net.UDPConn was the only supported type.
In the event of a future v2 of this module, this should be streamlined.
This is a backward compatible alternative to #1170 and supersedes it.
Fixes #1168
Closes #1170
> Support generic net.PacketConn's for the Server

- server.go
Missed this small typo in the just merged #1174.
> Fix PacketConnReader typo in DecorateReader docs

- client.go
Remove the newline so the comment is picked up as documentation.
> make the client.Exchange doc work

- svcb.go
When the priority is zero, the record is in AliasMode and so the value must be empty. This changes the comment accordingly.
> Fix comment about SVCB values in AliasMode

- README.md
- client.go
- doc.go
- tsig.go
- tsig_test.go
Here's another go at adding GSS-TSIG support.
Inspired by how crypto/ssh handles this I've defined a simple interface for an external GSSAPI implementation and added this to the `Client` and `Conn` structs. I've added two new internal `tsigGenerateGSSAPI()` and `tsigVerifyGSSAPI()` functions that are passed this interface and then refactored the original exported `TsigGenerate()` and `TsigVerify()` functions to use these, passing `nil` for the GSSAPI interface, so existing code using those will behave the same as before.
I've left the new functions unexported and I haven't touched the `Server` or `Transfer` structs yet. I've not added any tests either but that should be easy enough if you approve.
> Add GSS-TSIG support

- README.md
With #1201 merged, I've finalised my GSS-TSIG library. This PR is a link to my library.
By using the `TsigProvider` interface, it disables the original support for the HMAC TSIG methods so I wrote a version of that implementing the same interface. Rather than try and create a "super-provider" that supports every algorithm possible directly I borrowed an idea from the `io.Multi*` functions and wrote a `MultiProvider` that chains multiple providers together. If one provider returns `ErrKeyAlg`, the next provider in the list is tried.
So you can create a client that supports both sets of TSIG algorithms with something like this:
```golang
dnsClient := new(dns.Client)
dnsClient.Net = "tcp"
hmac := tsig.HMAC{"axfr.": "so6ZGir4GPAqINNh9U5c3A=="}
gssClient, err := gss.NewClient(dnsClient)
if err …
```
> Add a link to https://github.com/bodgit/tsig

- generate.go
- generate_test.go
These were flagged by GitHub CodeQL code scanning as potential vulnerabilities or issues. Fixing them is easy and they are incorrect. The triggered rule is `go/incorrect-integer-conversion`.
Adding tests is less easy because int is 64-bits on most systems, including those we test on, so we can't consistently provoke a failure here.
> Fix potentially truncated int casts in $GENERATE code

- dns.go
- edns.go
- parse_test.go
- scan.go
- scan_test.go
- tsig.go
- types.go
- update_test.go
RFC 3597 says we should allow parsing known record types in the "Unknown DNS Resource Record Type" format. This makes sense, zone files shouldn't become invalid simply because we learn a new concrete RR type or because other software doesn't recognise an RR type we support. The RFC also mentions instances where it can be preferable to use this format even in widely known RR types.
The concrete RR type will be returned for known record types. This is true even of ANY, NULL, OPT and TSIG records which would previously return a `*RFC3597` record.
Fixes #1209
/cc @madestro
> Support parsing known RR types in RFC 3597 format

- dns.go
- msg.go
- scan_rr.go
- scan_test.go
`(*RFC3597).fromRFC3597` failed to set `Rdlength` on the RR header. This is used (since yesterday) when parsing records from a zone file in the RFC 3597 "Unknown DNS Resource Record Type" format.
Also while we're here, validate the length doesn't exceed the maximum RDATA length when parsing in that format and harden `UnpackRRWithHeader`.
Updates #1211 (my bad)
/cc @catenacyber
> Fix Rdlength related parsing bug in RFC3597 records

- msg.go
- parse_test.go
This was split out of #1214.
I don't think this can be hit from `UnpackRR` as `unpackHeader` does validate it doesn't exceed `msg`, but it can definitely be hit by calling `UnpackRRWithHeader` directly.
> Validate Rdlength and off in UnpackRRWithHeader

- msg_truncate.go
This is a documentation update to highlight the behaviour of Truncate, which will reset dns.Compress to false when the message fits in the requested size without truncation, and make it the caller responsibility to set it back to true if they wish to compress, regardless of fitting, uncompressed, in the requested message size in the first place or not.
Fixes #1216
> Update Truncate doc with compress behaviour

- client.go
- client_test.go
- server.go
- server_test.go
Attempt to improve #1200.
This fixes #1199 and this is also crucial for #1218.
This way we'll continue to use `net.Buffers` for TCP connections and only switch to allocating a new buffer for TLS.
Regarding additional unit-tests, it seems that both code branches are already covered by existing unit-tests.
> Send DNS query in one packet when using TCP/TLS

- msg_helpers_test.go
- tsig_test.go
Noticed a non-gofmted `;` earlier, run gofmt -w -s on all files.
(mechanical change)
> Run a go fmt -w -s

- .github/workflows/go.yml
These are very out of date and it's causing persistent failures in the fuzz CI step. I hadn't paid much attention as I thought they were related to #1223, but I'm pretty sure it's because the go version is so out-of-date.
**Edit**: An example of the errors for posterity:
```
Error: /opt/hostedtoolcache/go/1.14.15/x64/pkg/mod/github.com/dvyukov/go-fuzz@v0.0.0-20210103155950-6a8e9d1f2415/go-fuzz-build/main.go:267:16: undefined: packages.NeedName
Error: /opt/hostedtoolcache/go/1.14.15/x64/pkg/mod/github.com/dvyukov/go-fuzz@v0.0.0-20210103155950-6a8e9d1f2415/go-fuzz-build/main.go:293:16: cannot use func literal (type func(*token.FileSet, string, []byte) (*ast.File, error)) as type func(*token.FileSet, string) (*ast.File, error) in assignment
Error: …
```
> Bump go versions in .github/workflows/go.yml

- .github/workflows/go.yml
The Fuzz step is still failing even after #1237. See these two runs on the master branch: https://github.com/miekg/dns/runs/2031876704 & https://github.com/miekg/dns/runs/2031876289. They failed even though the run for the #1237 PR succeeded: https://github.com/miekg/dns/pull/1237/checks?check_run_id=2027941443.
The problem is caused by github.com/dvyukov/go-fuzz/go-fuzz (and it's dependencies as it lacks a go.mod file) not being included in our go.mod file. For some reason the go command seems to be non-deterministically picking a version of golang.org/x/tools to download, sometimes picking one that's too old. I'm not sure why that is, and it feels like a bug in the go command or go module proxy.
We can either add it to our go.mod and go.sum files or remove the step. I think removing it …
> Remove fuzz from .github/workflows/go.yml

- .github/workflows/cifuzz.yml
The whole fuzzing pipeline is broken. Comment it out for now.
See #1186 and #1223
> stop doing any fuzzing

- scan.go
Add a couple of lines that we're not syntax checking.
Closes: #948
> zoneparser: document not checking syntax

- doc.go
> Remove HmacMD5 from the documention

- svcb.go
The problem with the current implementation is that it is not a real deep copy,
it points to the same base arrays behind the slices. This was causing some
issues in real-life application.
> Fix copy() in SVCBIPv4Hint and SVCBIPv6Hint

- scan_rr.go
When decoding a HIP resource record, 'base64.StdEncoding.DecodedLen' can return a length larger than the length of the decoded public key. This change decodes the public key and retrieves the correct length. In our tests, the public key length was being set to 33, instead of 32. Below is our offending resource record:
'23b5993f649c0827.a.b.c.      3600    IN      HIP     5 200100100020001523B5993F649C0827 Cm6k4jhir9YYoKq9JDqD3Ob1hBfCuwbWam1igFPhkGg='
> Incorrect HIP RR public key length decode

- edns.go
- msg_helpers.go
Make it more obvious that these two lists (const, and case) need to be
in sync.
Also sort the list to match the const sorting.
> Move makeDataOpt into edns.go

- update.go
- update_test.go
Prerequisite Section RRset Exist Value Dependent TTL must be zero.
```
2.4.2 - RRset Exists (Value Dependent)
A set of RRs with a specified NAME and TYPE exists and has the same
members with the same RDATAs as the RRset specified here in this
section.  While RRset ordering is undefined and therefore not
significant to this comparison, the sets be identical in their
extent.
For this prerequisite, a requestor adds to the section an entire
RRset whose preexistence is required.  NAME and TYPE are that of the
RRset being denoted.  CLASS is that of the zone.  TTL must be
specified as zero (0) and is ignored when comparing RRsets for
identity.
``
> fix Msg.Used TTL must be zero

- tsig.go
- tsig_test.go
Per RFC 8945 5.3.2, responses with BADKEY and BADSIG errors must not be signed.
> When a server detects an error relating to the key or MAC in the
incoming request, the server SHOULD send back an unsigned error
message (MAC Size == 0 and empty MAC).  It MUST NOT send back a
signed error message.
https://datatracker.ietf.org/doc/html/rfc8945#section-5.3.2
Signed-off-by: Chris O'Haver <cohaver@infoblox.com>
> Do not sign BADKEY and BADSIG TSIG error responses

- README.md
As requested on the README.md page. I've created a pull request to add a new application into the user mix.
It's not clear whether there is any order to this list, so I just added it at the end. Obviously that can be changed as needed.
> Add https://github.com/markdingo/autoreverse into list of README.md users

- msg.go
Fix location of opt pseudosection and prevent empty additional section in dig-like output
Before:
```
;; opcode: QUERY, status: NOERROR, id: 1234
;; flags: cd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; QUESTION SECTION:
;example.com. IN A
;; ADDITIONAL SECTION:
;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: do; udp: 512
```
After:
```
;; opcode: QUERY, status: NOERROR, id: 1234
;; flags: cd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: do; udp: 512
;; QUESTION SECTION:
;example.com. IN A
```
> Fix dig-like output

- client.go
- client_test.go
- server_test.go
Go supports three different types of unix connections `SOCK_STREAM` (unix), `SOCK_DGRAM` (unixgram) and `SOCK_SEQPACKET` (unixpacket) all of which are `*net.UnixConn`s. That means `*net.UnixConn` always implements `net.PacketConn` regardless of the socket type, though certain methods will return errors.
`SOCK_DGRAM` is the only one we want to treat as a packet connection and use the UDP framing for (IIUC). To do this we special case `*net.UnixConn`s and only treat `SOCK_DGRAM` as a `net.PacketConn`.
This will make it possible to properly use the DNS client over unix `SOCK_STREAM` connections (the most common type).
Fixes #1321
> Only treat a *net.UnixConn of unixgram as a packet conn

- client.go
- server.go
- tsig.go
- xfr.go
- xfr_test.go
This adds support for `TsigProvider` to both `Server` and `Transfer`. It also simplifies the implementation for `Client` and `Conn`.
Not sure why I didn't think to do this earlier. A miekg/dns/v2 could just push the `TsigSecret` code out into the callers.
This also has the advantage that it doesn't add a bunch of extra code paths throughout, so it's safer to land.
Fixes #1300
Closes #1323
Fixes #1325
> Support TsigProvider for Server and Transfer

- client_test.go
Using Exchange doesn't add anything, as it just wraps a client with a
default client.
Remove them and speed up the tests, goes from 3s to 1s (for the entire
test suite).
> Id check tests: stop using Exchange

- dnssec.go
- hash.go
- sig0.go
- sig0_test.go
This adds hash.go and creates a identityHash that is used for algorithms
that do their own hashing (ED25519) for instance.
This unifies the hash variable naming between dnssec and sig(0) signing
and removes the special casing that existed for ED25519.
This unifies the variable naming between sig(0) and dnssec signing and
verifying.
I didn't want to used crypto.RegisterHash as not to fiddle with the
global namespaces of hashes, so the value of '0' from AlgorithmsToHash
is handled specially in dnssec and sig(0) code.
<strike>Note that ED448 isn't implemented at all.</strike> Is not implemented in the standard libary
> Add identityHash for algos that don't need hashing

- edns.go
> Handle packing of empty RDATA correctly for EDNS0_EXPIRE (Resolves #1292)

- msg_helpers.go
- msg_helpers_test.go
If the PackBuffer is used to encode an NSEC/3 record, the bitmap is
xored with the content of the buffer instead of being zeroed first.
The algorithm has been changed so it is able zero bytes without
losing too much performance (around 2x slower).
> Invalid NSEC/3 bitmap on non-zero buffer

- dnssec.go
- dnssec_test.go
Of course the wording was changed (for the better) in an errata:
https://www.rfc-editor.org/errata/eid193
We still followed the original RFC4034 text. Note I haven't given this
much thought, just changed the 2 into a 3 and ran the test.
Fixes: #1352
> Fix RSAMD5 keytag calucation.

- example_test.go
> Fix ExamplePrivateHandle

- parse_test.go
- svcb.go
- svcb_test.go
The parameter is being added in [its own IETF draft][1] and also being used in
the [IETF draft about Discovery of Designated Resolvers][2].
Additionally, the mappings of the numeric key values to strings are exported,
under names consistent with the already existing exported mappings, to make it
easier for the clients of the module to validate and print SVCB keys.
Testing was done by sending SVCB queries for the "_dns.resolver.arpa" domain to
OpenDNS's 146.112.41.2 server.
[1]: https://datatracker.ietf.org/doc/html/draft-ietf-add-svcb-dns-02
[2]: https://datatracker.ietf.org/doc/html/draft-ietf-add-ddr-06.html
> Add SVCB dohpath key

- svcb.go
> Add notes about SVCB draft changes to SVCB-related API

- example_test.go
Small fix in the examples to properly work with v6 addresses.
Closes: #1365 #1367
> Fix examples by using net.JoinHostPort

- parse_test.go
- svcb.go
- svcb_test.go
PR for #1361 
This code adds more comprehensive parsing and string conversion to the alpn support in the HTTPS/SVCB types.
Before we were just splitting on `,`, but this version actually parses as per the draft, which allows alpn with a `,` in the value. This adds a ton of error cases and a fair bit of code, so I'm hoping the RFC simplifies this to just forbidding `,` in the alpn completely (am I too late to suggest that?). On the plus side, the examples in the tests now actually return correct values.
I used the existing `nextByte()` function in the `types.go` file, since I needed the same functionality. This means that we allow incorrect values like `\456`, but I figured fixing that was out of scope. Is it worth a separate PR? :thinking: Note that the parser for `SVCBLocal` uses …
> Properly parse alpn values in SVCB

- parse_test.go
- svcb.go
I noticed that the brand-new dohpath support has a similar problem to the one addressed in PR #1361 - non-printable characters are not handled properly.
Luckily the parameter is much simpler than the alpn parameter. I refactored the parse/stringify `SVCBLocal` out and use that for both types.
> Fix dohpath parsing/stringify

- defaults.go
- labels_test.go
- msg.go
We noticed that `IsDomainName()` was allowing names that start with at `.`. This is an error, which this PR fixes.
> Disallow names that start with '.' in IsDomainName()

- msg_helpers.go
Add 'in the type bitmap' to make clear where in the RR the error occurs.
Also use 'NSEC(3)' - as this code is shared between NSEC and NSEC3, the
first error used NSECx.
Technically backwards incompatible, but checking strings in errors as
bad practice (although this lib lacks library types).
See #1373
> Add more detail to NSEC packing errors

- client.go
- client_test.go
- server_test.go
This was broken by PR: https://github.com/miekg/dns/pull/1322
> Add back support for *net.UnixCon with seqpacket type

- client.go
- server.go
- tsig.go
- tsig_test.go
- xfr.go
Make it public as TsigGenerateWithProvider and update the docs a little.
> Make tsigGenerate/VerifyProvider public

- LICENSE
I've found a way to incorporate your copyright so that GitHub still recognizes it as a BSD-3-Clause license.
This will allow [the GitHub API](https://docs.github.com/en/rest/licenses#get-the-license-for-a-repository) to report a license rather than `NOASSERTION` as it does now.
Hopefully you will be happy to merge this?  
Thank you in advance for your consideration.
> Restructure license so Github will recognize it.

- doc.go
fixes invalid syntax in one of the examples of the README
> fix: example in docs with invalid syntax

- README.md
This is currently used to provide DNS server capabilities to the nebula lighthouses.
> Add slackhq/nebula to users of the library

- edns.go
Adds to `opt.String()` making the opt printing more like dig.
The &0x7FFF is like dig, which doesn't display the DO flag even when set (see below)
```
❯ dig +ednsflags=12 +expire github.com +qr +dnssec
; <<>> DiG 9.18.4-2-Debian <<>> +ednsflags +expire github.com +qr +dnssec
;; global options: +cmd
;; Sending:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56825
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; MBZ: 0x000c, udp: 1232
; COOKIE: 
; EXPIRE:
;; QUESTION SECTION:
;github.com.                    IN      A
;; QUERY SIZE: 55
```
> edns: add missing dig options

- labels.go
This was mistakenly added in #1406.
> Remove space between NextLabel func and doc comment

- README.md
https://github.com/egbakou/domainverifier is a domain name ownership verification library written in go.
It uses this project to implement both the TXT record and CNAME record verification methods.
> doc: added egbakou/domainverifier as user

- msg.go
- msg_helpers.go
This allocation and the copy of s are both pointless.
> Eliminate tmp buffer from packTxtString

- client.go
This has been a long standing TODO we can cross off as tls.Dialer is well supported now.
> Use tls.Dialer in Client.DialContext

- listen_no_reuseport.go
- listen_reuseport.go
- server.go
This is well outside our supported release range.
> Remove pre-go1.11 support from reuseport code

- udp_windows.go
These TODOs were not correct as x/net/ipv4 and x/net/ipv6 still don't have Windows support.
Updates #738
Updates #765
Updates coredns/coredns#2138
See golang/go#7175
See golang/go#7174
> Correct TODO in udp_windows.go

- defaults.go
- msg.go
- types.go
We use generics to merge `dddToByte` and `dddStringToByte`.
We also introduce a generic `isDDD` helper that replaces nearly all uses of `isDigit`. The exception being `svcbParseParam` which implements stricter parsing.
> Use generics for ddd escape parsing

- types.go
- types_test.go
https://www.rfc-editor.org/rfc/rfc1876
> Updates to LOC type RFC1876

- clientconfig_test.go
- generate_test.go
- scan_test.go
[ioutil](https://pkg.go.dev/io/ioutil) go deprecated as of go 1.16 so let's not use it and use replacements from e.g. `io` package.
> chore: don't use deprecated ioutil package

- defaults.go
- dns_test.go
While this code may be slightly less clear, it's significantly faster and this function seems to be a hot path for certain workloads.
This function still has significant overhead for names that have an escape sequence immediately before the final dot. While an important edge case to handle, these should be vanishingly rare with most callers noticing the speedup. This change even offers a rather decent performance improvement for these names anyway.
I tried splitting `IsFQDN` into a fast and slow path for better inlining, but couldn't get it below the inlining threshold no matter what I tried, so I have left it as one function.
```
name                 old time/op    new time/op    delta
IsFQDN/no_dot-12       5.86ns ± 2%    1.48ns ± 3%  -74.71%  (p=0.000 n=10+10)
IsFQDN/unescaped-12 …
```
> Improve IsFQDN performance

- parse_test.go
- scan_rr.go
Java outputs these *and* the RFC says we should parse them, so parse
them. We'll never output them though. Throwback to the "be lenient to
what you accept, but strict with what you output". Anyhow the diff is
tiny and it helps interop.
Fixes: #1447
> Allow RRSIG algorithm mnemonics

- client.go
If we want to use a custom mechanism of obtaining a Conn that doesn't match the net.Dialer type, but retain the timeout behaviour from ExchangeContext, there was previously no way to accomplish this.
This PR makes the underlying ExchangeWithConnContext function public, which allows this behaviour.
Now that #1454 is merged, there is no longer any interaction between the context provided and the singleflight behaviour, so I removed the comment from ExchangeWithConn.
> Make ExchangeWithConnContext public

- msg.go
- update_test.go
When `Opcode` == `OpcodeUpdate`, `String()` should use section names as described in [RFC 2136 Section 2](https://datatracker.ietf.org/doc/html/rfc2136#section-2):
Query -> Zone
Answer -> Prerequisite
Authority -> Update
> Use proper section names when producing dig-like output for UPDATEs

- parse_test.go
- types.go
In order to parse an IPv4 address encoded as IPv6, it needs to have the prefix of "::ffff:", i.e. ::ffff:192.0.2.1
This allows export of parsed IPv4 encoded IPv6 AAAA records to be scanned back to a valid AAAA record.
Without it the following code fails as the address is "plain" dotted IPv4-format:
```
rr, err := dns.NewRR(". 1 IN AAAA ::ffff:192.0.2.1")
if err != nil {
log.Fatalf("parse failure: %w", err)
}
_, err = dns.NewRR(rr.String())
if err != nil {
log.Fatalf("parse failure: %w", err)
}
```
This comes from the std libs net.IP String() function which outputs IPv4-in-IPV6 as standard dotted-IPv4. net/netip.Addr type, in contrast, differs here in that the String() func outputs it with the proper prefix "::ffff:" Ref: https://pkg.go.dev/net/netip#Addr.String
The other attempt to fix …
> Use correct string format IPv4 encoded as IPv6 for for AAAA records

- README.md
Before `sdns` was added to users list but deleted some reasons. I read the reasons but the project never be selling anything nor nxdomain/404. That was described like that on https://github.com/miekg/dns/commit/68df4402de4a2303c8dad5aea62450485d589d81
Could you please check and add again? 
Thanks.
> readme: add sdns to users

- .github/workflows/go.yml
> up go version for testing

- edns.go
As I identified in #1460, there is a mistake in the documentation appeared, that I would like to address through the following pull request.  I've tried to change as few symbols, as possible, to keep the documentation comprehensive and concise.
Best regards, @EugeneOne1.
> The small `(*dns.OPT).SetDo` documentation tweak

- acceptfunc.go
The check was removed in https://github.com/miekg/dns/issues/975.
> Remove comment about checking zero bit.

- defaults.go
This function was previously changed from using `strings.ToLower` to a custom loop to ensure it only lowercases ASCII characters. This was more complicated than it needed to be and introduced more allocations than is necessary.
Instead of that approach we call `strings.Map` with a simple ASCII lowercase mapping function. Sadly we still use the nice ASCII-only fast path that `strings.ToLower` had, but it's unlikely to be worth all the extra code.
Updates #1434
Updates #1470
> Simplify CanonicalName

- defaults.go
Allow SetReply to be called against the request message, ie:
```
r.SetRcode(r, dns.RcodeNameError)
w.WriteMsg(r)
```
If not, r.SetRcode(r, dns.RcodeNameError) will reset Question section to empty.
> Make SetReply a Reflexive Operation

- dnssec_keyscan.go
- generate.go
- msg_generate.go
- scan.go
- svcb.go
- types_generate.go
`strings.Split` has to allocate for the return slice. This allocation was wasteful in ever case it was used in this library.
Instead we use the new `strings.Cut` and other string manipulation where appropriate. This tends to lead to cleaner and more eadable code in addition to the benefits this has on the garbage collector.
> Avoid using strings.Split

- defaults.go
This is a very minor change that simply neatens up this function. Behaviour is identical.
> Cleanup IsRRSet

- msg.go
- msg_helpers.go
This is exactly the same change as #1429 but for `packOctetString`.
I have no idea how I missed this given it's the very next function.
Updates #1429
> Eliminate tmp buffer from packOctetString

- msg_helpers.go
We definitely shouldn't be using `goto` for a simple loop.
This is technically a behaviour change when `off == len(msg)`, but we're always called with `off < len(msg)` so this is unobservable.
> Avoid using a goto loop in unpackDataOpt

- scan_rr.go
This will cause one less allocation as `String` allocates on a `bytes.Buffer` but not on a `strings.Builder`.
> Use strings.Builder in endingToString

- scan.go
No one has complained about this in the four years it's been here. I think we can safely accept this new behaviour.
> Remove slurpRemainder TODO from (*ZoneParser).Next

- xfr.go
This PR swaps the order in which the connections and channels are closed in `inAxfr` and `inIxfr`. This makes the order more logical (consumers of the channel can be sure that the connection has been closed when the channel is closed).
The motivation for changing this is a heisenbug we had in our test pipeline. After closing the channel, the test code checked if the connection had been closed as well. Due to the nature of go routines, the test would randomly fail, depending on the scheduler. Swapping the order eliminates the problem, putting both deferred calls into the same function may even give (a very slight) performance improvement and it makes the order of operations more predictable and logical.
If you have any questions or suggestions I'm happy to incorporate them.
-- Tim
> Swap closing order in `inAxfr` and `inIxfr`

- dnssec_keyscan.go
- generate.go
- privaterr.go
- scan.go
- scan_rr.go
- scan_test.go
- svcb.go
This adds ZoneParser.SetIncludeAllowedFS, to specify an fs.FS when enabling support for $INCLUDE, for reading included files from somewhere other than the local filesystem.
I've also modified ParseError to support wrapping another error, such as errors encountered while opening the $INCLUDE target.  This allows for much more robust handling, using errors.Is() instead of testing for particular strings (which may not be identical between fs.FS implementations).
ParseError was being constructed in a lot of places using positional instead of named members.  Updating ParseError initialization after the new member field was added makes this change seem a lot larger than it actually is.
The changes here should be completely backwards compatible.  The ParseError change should be invisible to …
> Allow use of fs.FS for $INCLUDE and wrap errors

- scan_rr.go
- types.go
- zduplicate.go
- zmsg.go
- ztypes.go
This add the NXT record (2535) to implement all records from the RFC.
Also does a s/RFC RFC/RFC/ as I happen to bumb into that will editing
the comments.
> Add NXT record

- README.md
- parse_test.go
- scan_rr.go
- types.go
- zduplicate.go
- zmsg.go
- ztypes.go
We had the type code, this add the rest. Other RRs from 1183 are also
fully impl. don't know why this one wasn't.
> Add ISDN record

- scan.go
In particular, document the default origin.
> Improve NewRR documentation

- xfr.go
- xfr_test.go
Add a new helper func InTLS to start a zone transfer using a TLS connection
> Add option to do a zone transfer via TLS

- defaults.go
- scan_test.go
Keep track if the escape, if still true when returning isDomainName
should return false.
TODO:
- Should still be done in packDomainName as well.
- And that should be tested
- Some tests now fail
There are multiple other places that supposedly also check for this, but
they are not called in the parsing.
Fixes: #1528
> IsDomainName: check for escape as last character

- parse_test.go
- scan_rr.go
- scan_test.go
`endingToTxtSlice`, used by TXT, SPF and a few other types, parses a string such as `"hello world"` from an RR's content in a zone file. These strings are limited to 255 characters, and `endingToTxtSlice` automatically splits them if they're longer than that. However, it didn't count the length correctly: escape sequences such as `\\` or `\123` were counted as multiple characters (2 and 4 respectively in these examples), but they should only count as one character because they represent a single byte in wire format (which is where this 255 character limit comes from). This commit fixes that.
> Fix counting of escape sequences when splitting TXT strings

- scan_rr.go
- scan_test.go
Also, reorganize the function a bit to make it more readable. Details here: https://github.com/miekg/dns/pull/1540#issuecomment-2065854334 (and in the commit messages)
> Fix possible out-of-bounds read in endingToTxtSlice

- acceptfunc_test.go
- server.go
Currently there are hooks for reading messages off the wire (DecorateReader), checking if they comply with policy (MsgAcceptFunc), and generating responses (Handler).  However, there is no hook that notifies the server when a message is dropped or rejected due to a syntax error.  That makes it hard to monitor these packets without repeating the parsing process.
This PR adds a hook for notifications about invalid packets.
> Add a hook to catch invalid messages

- parse_test.go
- svcb.go
- svcb_test.go
Hi folks!
The IETF just recently published a new [RFC 9540](https://datatracker.ietf.org/doc/rfc9540/). It introduces a new SVCB parameter `ohttp` to a service binding DNS RR to indicate [Oblivious HTTP](https://datatracker.ietf.org/doc/rfc9458/) is available on the target host. Note that the value is always empty. It can be either used in the HTTPS SVCB or in the SVCBs for DDR (Disovery of Designated Resolvers) (see [RFC 9462](https://www.rfc-editor.org/rfc/rfc9462.html)). 
I've added the new SVCB type and added also the tests from the different RFCs.
> Add RFC 9540 to SVCBs to indicate Oblivious HTTP is available

- README.md
Looks like AAAA records and "ip6.arpa" are supported, so add this to the list.
Hope this helps.  Have a nice day.
> Add rfc3596

- edns.go
Extended DNS Error (EDE) codes were missing for code points 25-30. These are documented in:
https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#extended-dns-error-codes
I was going to add support for EDE code 30 and noticed that also EDE codes 25-29 was missing so I added those as well
> Add support for missing Extended DNS Error Codes (EDE)

- types.go
- zduplicate.go
- zmsg.go
- ztypes.go
IANA har allocated the NXNAME meta type to indicate an NSEC/NSEC3 record signals that the name does not exist (corresponds to NXDOMAIN). NXNAME is a meta type only for use with NSEC/NSEC3 bitmaps and use is defined in https://datatracker.ietf.org/doc/draft-ietf-dnsop-compact-denial-of-existence/
> Add support for NXNAME type

- server.go
net.Error.Temporary has been deprecated since Go 1.18. There has been some discussion around what to use in server accept loops instead [1], but the suggestion seems to be that it may be a mistake to have any sort of retries in place [2].
This PR removes it, which may expose some users to errors that were previously swallowed and retried, but at the expense of leaking file descriptors and the like.
1: https://groups.google.com/g/golang-nuts/c/-JcZzOkyqYI/m/xwaZzjCgAwAJ?pli=1
2: https://groups.google.com/g/golang-nuts/c/-JcZzOkyqYI/m/vNNiVn_LAwAJ
will …
> Remove use of deprecated net.Error.Temporary

- server.go
This reverts commit ef7392e4ff2ef86bea51ee4f32fc60eaf1c2a88a.
See:
https://github.com/miekg/dns/pull/1589#issuecomment-2276738695
breaks udp serving
> Revert "Remove use of deprecated net.Error.Temporary (#1589)"

- server.go
The bytes read from the reader are returned to a pool and
must not be changed by the decorated reader.
Fixes #1578
> add decorate reader warning

- edns.go
Mostly trickered by:
~~~
-               return &EDNS0_ESU{Code: EDNS0ESU}
+               return new(EDNS0_ESU)
~~~
dont see why this 'case' needs to be different than all the others. Some various textual changes for the test.
> edns0 cleanups

- listen_no_socket_options.go
- listen_socket_options.go
- server_test.go
Currently it is impossible to set both `SO_REUSEADDR` and `SO_REUSEPORT` simultaneously. If a user tries to set both, there is no error and none of the options are actually set which can be quite confusing.
This PR not only fixes this but adds a test for all combinations of the socket options. In contrast to the existing tests for `SO_REUSEADDR` and  `SO_REUSEPORT`, this test does not check that the options do what they are supposed to do (this is the kernels responsibility) but it tests whether or not the options are actually set as requested by the user (which is the library's responsibility).
> Allow SO_REUSEADDR and SO_REUSEPORT to be set simultaneously

- README.md
Hey miekg/dns maintainers!
I help manage the ZDNS fast DNS lookup utility and we use miekg/dns as our underlying dns library. Would love to add our project as a user in the `README.md`. Thanks for all your work!
> User Addition: add ZDNS as a user of miekg/dns

- dnssec.go
- dnssec_test.go
- sig0.go
Maybe not a perfect fix, but this attempts to resolve #1617.
Also introduces tests to ensure compliance with RFC 4035.
> fix: input validation for RRSIG.Verify()

- README.md
- svcb.go
> SVCB is now RFC 9460.

- README.md
- edns.go
- edns_test.go
Compact Answers OK flag is a signal that a queryer or server understand and can validate Compact Denial of Existance answers allowing RCODE NXDOMAIN restoration with single NSEC/NSEC3.
Flag is allocated by IANA: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-13 Compact Denial of Existance: https://www.iana.org/go/draft-ietf-dnsop-compact-denial-of-existence-07
> Add support for Compact Answers OK flag in EDNS

- README.md
- scan_rr.go
- types.go
- zduplicate.go
- zmsg.go
- ztypes.go
Adds the RESINFO rr type from [RFC 9606](https://www.rfc-editor.org/rfc/rfc9606.html) (DNS Resolver Information).
RESINFO uses the same format as TXT.
> Add RESINFO rr

- udp.go
- udp_no_control.go
sendmsg with PKTINFO is broken on darwin, so don't use it
udp_windows is renamed to udp_no_control since it's no longer exlusive to windows, and is used on darwin too
fixes #724 and #941
> Avoid sendmsg control messages on darwin

- scan.go
- scan_test.go
> Return error for empty target

- xfr.go
- xfr_test.go
Hi! 
This fixes a possible bug where a xfr client can skip tsig validation if the server doesn't respond with a tsig. 
Say I setup an xfr client with a tsig provider. If it connects to a server which doesn't implement tsig, but that server can perform a transfer without adding the tsig to the response then the current logic will skip validation. 
`m.IsTsig() && t.tsigProvider()` is going to look for the tsig in the message, see none and consider the transfer valid, but I think the client should be checking the signature since the tsig provider is configured on the client.
> Fix logic in xfr ReadMsg + add test

- server.go
Adds `Net() string` to `ResponseWriter` which returns the corresponding `Server`'s `Net` value (e.g., "tcp", "tcp-tls").
This makes it easy, for example, to gate logic in a `Handler` based on the transport protocol, such as adding EDNS0 Padding to responses when using TLS.
Cheers!
> Add ResponseWriter.Net function

- msg.go
- msg_generate.go
- zmsg.go
Here's a first stab at the code for #1576 
This commit adds annotations to the error message when an error occurs during unpacking of a DNS message, the annotation will give detiail on where in the DNS message the unpacking error occured at. This helps to improve the debugability of such errors.
> Annotate unpack* function errors with where the error happened.
