miekg/dns

dns_test.go
server_test.go
xfr_test.go

Fix problems noted by 'go vet'

Fix problems noted by 'go vet'

---

dnssec_keyscan.go

Use algorithm number to determine private key type.

---

parse_test.go
types.go
zscan_rr.go

this will continue, comments are welcome but I noticed that some odd types are not quite supported fully (HINFO, SSHFP) and some, have updated RFCs that need lib changes (NSAP).
I expect to commit more to this PR.

Changes for rarely-used RR types

---

client.go

In addition to #220 I found small issue in client that was not using constant as it probably was intended to do.

Minor fixes (see description)

---

idn/punycode.go
idn/punycode_test.go

change function return behaviour on error

---

README.md

Read more here: https://blog.cloudflare.com/dns-parser-meet-go-fuzzer/

Added Cloudflare to the user list.

---

README.md

I wrote an experimental Android app to make DNS queries. It uses this library behind the scenes. Additional info : http://www.sajalkayan.com/post/android-apps-golang.html

Adding DNS debugger android app

---

idn/punycode.go
idn/punycode_test.go

Avoid rune overflow when converting to unicode

---

server.go

This avoids some issues with Server.PacketConn and Server.Listener being accessed outside of their locks.
Fixes #244.

fix some data races in Server

---

doc.go

Fixing typo. Msg is undefined and should use dns.Msg

Updating doc.go

---

client.go

The current code sets the read deadline at the same time as the write
deadline. If the write nearly times out but doesn't, the read timeout
can fire before the read happens within the specified deadline.

client: SetReadDeadline after write, before read

---

server.go

If I understand correctly what you might have meant here.
Fixes #282

Only re-try AcceptTCP() if the error is temporary

---

doc.go

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

doc: example shows a conditional with non-bool

---

client.go
msg.go
server.go
zgenerate.go

Hi, thanks for a great package.  I ran it through client9/misspell and found a few nits.  Regards, -nickg

minor spelling corrections

---

dnsutil/util.go
dnsutil/util_test.go
labels.go
labels_test.go

* TrimDomain() Trims the domain off a FQDN.
* AddDomain() Adds a domain to a shortname.
* GenerateZoneFile() Create a pretty BIND-style Zonefile.

Added new functions: TrimDomain(), AddDomain(), GenerateZoneFile()

---

README.md

Adding [dnslookup.org](https://dnslookup.org) to the list of users.

New user added

---

README.md

Proof: https://github.com/hashicorp/consul/blob/master/command/agent/dns.go

Add consul to list of users on README

---

udp_other.go
udp_plan9.go

note that i'm unsure if this code really works, but it allows github.com/xenolf/lego/acme to build on 9front.

fix building on plan9

---

client.go
client_test.go

This change allows limiting the duration of the complete dial, write, read cycle, as opposed to controlling them individually.

Add Client.Timeout to allow limiting total exchange duration

---

README.md
edns.go
msg.go

If you're interested, a small patch to add EDNS0 cookie support.

small patch for EDNS0 cookie support

---

msg.go

Check length before packing OPT

---

dnssec_keyscan.go

Hello!
I hit panic with blank string specified to NewPrivateKey() function. So I decided to add sanity check to it.
Thank you!

Add sanity check to NewPrivateKey

---

msg.go
server.go

Noticed some golint errors, cleaned them up. There are more, can try to go through them as well.

Some golint fixes

---

README.md

Which is a resolver for docker machines.
And thanks for this great lib :+1:

readme - add dockness to user list

---

privaterr_test.go

Change VERSION private RR to use reserved space

---

msg_generate.go
zmsg.go

Fix packing compression according to struct tagging

---

README.md
client_test.go
dnssec.go
edns.go
reverse.go
server_test.go
smimea.go
types.go
types_generate.go
update_test.go
ztypes.go

Golint fixes

---

dnssec.go
zcompress.go

and add one golint/doc fix intoit.

Re-gen zcompress.go

---

msg.go

Don't set Compress to false on dns to calucate the uncompressed length,
instead a a function where the compression is a flag and use that.

msg.go: don't fiddle with Compress

---

msg.go

limiting domain names to 255/63 octets/labels

---

msg.go
msg_test.go

Domain names must not exceed 255 octets in wire format.
Ref gh-463
Ref gh-469

Domain name limits

---

msg.go

Minor fix - thanks for the library!

Fix minor typos in comments

---

README.md

https://www.dnsperf.com/ is using this library to run the dns benchmarks :)

Added dnsperf to users

---

client.go
client_test.go

These obey the timeouts provided in a Context.
Relates to #336

Add ExchangeContext methods.

---

client.go
client_test.go
dns_test.go
msg_helpers.go

I found some places where err variables were being ignored.

Fix ignored err variables.

---

types.go

I pulled these from https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
I kept having to look up which one was NXDomain ;)
This is quite verbose so I can remove some of the columns or change the formatting if you want.

document RCodes from the IANA registry

---

xfr.go

make IXFR standard compliant

---

edns.go
edns_test.go
msg.go

This pull request fixes issue #516.

Fix EDNS Extended RCODE

---

README.md

Add Apex in Users

---

client_test.go
dns_test.go
dnssec_test.go
labels_test.go
parse_test.go
privaterr_test.go
sanitize_test.go
server_test.go
update_test.go
xfr_test.go

Move some of them to Errorf and friends, but most of them are just
gone: This make go test -v actually readable.

Test: remove all Logf/Log

---

client_test.go
server.go

This reverts commit 8223ae840e47f0c9a1ea1d5c22bdd03b30b6b3cf.

Revert "server: drop graceful handling (#546)"

---

client_test.go
nsecx_test.go
parse_test.go
server_test.go
types_test.go

This increases the test coverage as these methods where not tested.
Add some cosmetic changes to the mix.

Tests: add ListenAndServe tests

---

client_test.go

See issue #575. Try to fix (and maybe trigger it)

Test: rework concurrentExchange

---

parse_test.go
scan_rr.go

I'm fuzzing the text parser and that turned up these two. Will do
further fuzzing with these fixes in.

Fuzzing the text parser: a few fixes

---

doc.go
parse_test.go

A few spelling fixes I noticed via the `misspell` static analyzer.

Spelling fixes

---

edns.go
sanitize.go
scan_rr.go
xfr_test.go

Some linter fixes from Go report card.

---

client.go

This makes `client.Readmsg` always return the message,
regardless if and how unpacking the message failed.

Fix issue #605

---

server.go

This reverts commit ac8cd7878c723b698420572df92b293dd041d9ff.
See #619

Revert "Fixes #613 (#617)"

---

server.go

See https://github.com/miekg/dns/issues/619#issuecomment-356268848 for the rationale.
Fixes #613 
Fixes #619

Fixes #613 & #619

---

server.go

See https://github.com/miekg/dns/issues/619#issuecomment-356270075 onwards for rationale.

Ignore malformed UDP datagrams with incomplete DNS headers

---

msg.go

This function allow to extra the raw content of a record type based on
an existing header.
Fixes #633

[msg] Add UnpackRRWithHeader

---

client.go

This makes `Conn` safe for concurrent use if the message doesn't have a TSIG record.

use a local variable to calculate rtt

---

udp.go

In the course of solving #660, I cleaned up and simplified a few parts of `udp.go`.

Cleanup udp.go somewhat

---

server.go

This is a reland of #653 after it was reverted in an attempt to track down #660. The pull request is identical to #653.

Cleanup serve function (reland)

---

dnssec.go

Discussion in issue https://github.com/miekg/dns/issues/669

Add DSA to SHA1 mapping in dnssec AlgorithmToHash

---

msg.go

Small comment tweaks

---

client.go

Latest draft uses "application/dns-message".

doh: Fix mime type

---

dnssec.go

RFC 2537 (RSA/MD5) and RFC 3110 (RSA/SHA1) disallow leading zero octets.
RFC 5702 (RSA/SHA256 and RSA/SHA512) isn't specific but defers to these
earlier RFCs in other places.
There is an upper limit of 4096 bits for both the modulus and exponent.
The modulus must be at least 512 bits. No minimum is specified for the
exponent but a quick search suggests single byte exponents are viable.
Exponents larger than 32 bits are already disallowed. This commit adds
checks for the other requirements, general bounds checks, and defers
initialisation of the big num till the other checks have passed.

Harden RSA public key unpacking

---

types.go
zcompress.go
zmsg.go

This type should not compress its rdata.
Fixes #521

Remove compression from AFSDB

---

README.md

Hi Miek,
I have used your awesome dns package to implement native SSHFP checking for ssh.Client. I added my package to the readme. It seems nobody has created a package for this, but messing around with known_hosts files is cumberstone.
Kind regards,
Jerry

README.md: Add github.com/xor-gate/sshfp

---

msg_helpers_test.go

Signed-off-by: Lorenzo Fontana <lo@linux.com>

Add testcases to validate consistency of packDataNsec

---

server.go

This moves the `srv.started` checking with it's `srv.lock` dance out of `serveUDP` and `serveTCP`, and into a separate function. Once rebased, this might make the changes in #713 slightly cleaner. I believe this is worth doing independently of #713 though.

Abstract shutdown checking into seperate function

---

server.go

The meaning of this const has come up in both #722 and #725, so it's clearly non-obvious. Hopefully this wording will clarify things.
/cc @UladzimirTrehubenka

Improve documentation of maxWorkersCount const

---

scan_rr.go
scan_test.go

Fix ParseZone() parsing error #742 
- fix error comparison in setTA() in scan_rr.go
- add testcase to make sure everything is ok

Fix issue #742

---

client.go
dns_test.go
dnssec_test.go
msg.go
msg_test.go
privaterr.go
scan.go
scanner.go
server.go
sig0.go
udp_test.go

These were all caught with the various tools from [dominikh/go-tools](https://github.com/dominikh/go-tools).

Fix dominikh/go-tools nits

---

server_test.go

This has always bothered me as it's a lot of code to do very little.

Replace the trigger type with chan in server_test.go

---

server_test.go

Instead of having a separate `RunLocalUDPServerUnsafe`, we can use the functional options added to `RunLocalUDPServerWithFinChan` in ab16005053.

Remove RunLocalUDPServerUnsafe test method

---

client.go
client_test.go
leak_test.go

After seeing https://github.com/semihalev/sdns *is not* using any of the build in DoH stuff I became more convinced we should not attempt to do things in this library.

Revert doh

---

README.md
doc.go

doc: Clean up README and doc.go

---

msg.go

Use range loop in packBufferWithCompressionMap

---

client_test.go

This test currently fails on occasion due to what appears to be goroutine scheduling differences. This should eliminate those failures.
Fixes #752

Make TestTimeout less flaky

---

defaults.go

Use strings.HasSuffix for IsFqdn

---

format.go

Remove unused variable from switch in Field

---

msg_generate.go
zmsg.go

This is consistent with the pack*() functions and is idiomatic Go.

Return nil error from final return in unpack*()

---

acceptfunc.go

Make defaultMsgAcceptFunc a func not a var

---

dnssec.go
reverse.go
types.go

This is cosmetic, but keeps thing more uniformly organised.

Move all reversed map creation into reverse.go

---

README.md

Add Render to list of users

---

duplicate.go
duplicate_generate.go
zduplicate.go

Hello, I found a misspelling in `isDuplicateName` function name. Fixed it.

Fixed a misspelling.

---

server.go

Manually revert the worker model.

Manually revert worker's goroutine 98a1ef45

---

server.go

Move this code to the server's init function to get it out of the
hotpath.

Move srv.Handling selection to init()

---

client.go
server.go

This is much cleaner than the existing code and it avoids copying the message buffer. This should see a (small?) performance improvement for TCP connections, while possibly being a (small?) performance loss for TLS connections.
I want to similarly clean up the TCP reading code, but I'm not quite sure how best to handle the subtle error dance.

Use net.Buffers for writing TCP message

---

format.go
format_test.go

Fixes panic when parsing A or AAAA records with no data

Add checks on data length for A and AAAA records

---

fuzz_test.go
msg_test.go

Run gofmt -w -s

---

msg_helpers.go

Smaller, simpler, and (imperceptibly) faster by always doing everything in a single loop and keeping a bookmark rather than a `WriteByte` for every unescaped character:
```
$ go test -benchmem -bench=UnpackString >benchmark.new.txt && benchstat *old*txt *new*txt
name                      old time/op    new time/op    delta
UnpackString/Escaped-8       100ns ± 0%      96ns ± 0%   ~     (p=1.000 n=1+1)
UnpackString/Unescaped-8    55.1ns ± 0%    53.8ns ± 0%   ~     (p=1.000 n=1+1)
name                      old alloc/op   new alloc/op   delta
UnpackString/Escaped-8       32.0B ± 0%     32.0B ± 0%   ~     (all equal)
UnpackString/Unescaped-8     32.0B ± 0%     32.0B ± 0%   ~     (all equal)
name                      old allocs/op  new allocs/op  delta
UnpackString/Escaped-8        1.00 ± 0% …
```

Simplify unpackString

---

xfr_test.go

Signed-off-by: Lehner Florian <dev@der-flo.net>
This PR simplifies a loop.

simplify loop

---

edns.go
edns_test.go
msg_helpers.go
ztypes.go

This reverts commit a98e771ba54f32f7273c037cb8a6e7a7aef6a654.
This is breaking people

Revert "Export EDNS0 interface (#1041)"

---

msg_helpers.go

Currently EDNS0 Data unpack for EXPIRE option isn't implemented yet.

Add missing EDNS0EXPIRE data unpack

---

xfr.go

The currently example code has a data race, put in the proper code.
Fixes: #1061

doc: fix xfr example.

---

README.md
duplicate_generate.go
msg_generate.go
msg_helpers.go
msg_helpers_test.go
parse_test.go
scan_rr.go
types.go
types_generate.go
zduplicate.go
zmsg.go
ztypes.go

This PR adds support for [APL record type](https://tools.ietf.org/html/rfc3123).

APL record support

---

defaults.go
doc.go
duplicate.go
labels.go
nsecx.go
privaterr.go
scan.go
types.go
version.go
version_test.go

Was reading https://pkg.go.dev/github.com/miekg/dns?tab=doc and spotted
some types and things to could be slightly better.
Make v unexported, as this version stuff should not be part of the
public API.

Doc updates

---

server_test.go

In `TestServerRoundtripTsig(*testing.T)` (`server_test.go`), the TSIG handler is never invoked, because the default `(*dns.Server).MsgAcceptFunc` rejects queries with `OpcodeUpdate`.
*(This is extracted from #1077, but independent of that PR)*

Improve TSIG test

---

msg_helpers.go
msg_helpers_test.go

fix AFDLENGTH  and AFDPART length check.

fix APL address length check.

---

msg_helpers.go

- Don't try to fill if it's going to overflow (It used to fill until it can't fill, and then `continue`. There was a bug: If that branch was run with the last element of the loop, then continue act as break and an error wouldn't be returned)
- Factorize multiplied code

Cleanup EDNS

---

generate.go

fix failing tests on 32 bit platforms

---

msg.go
types.go
types_test.go

Be consistent about domain name label character escaping

---

README.md

Thanks for making this great library, Miek!

Add domainr.com & zonedb.org to the Users list

---

README.md

Thanks for the great library!
I couldn't quite figure out the sort order so I put my link at the end...

add link to https://github.com/fortio/dnsping

---

.github/workflows/cifuzz.yml

and run it for 5 minutes instead of 10
Cf #1186 cc @tmthrgd

Runs CIFuzz only when go files are modified

---

README.md

Adding a shameless plug to my Prometheus exporter. ;) Thanks for sharing your code on here.

Add a link for dnsbl_exporter

---

README.md

Try to keep this list semi up to date.

readme: add CAA and ZOMEMD RFCs

---

README.md

Signed-off-by: Nikolay Nikolaev <nikolay.nikolaev@konghq.com>

readme: adding Kuma.io

---

server.go

Detail: https://github.com/miekg/dns/issues/1226

Close the UDPConn before returning if setUDPSocketOptions fails

---

parse_test.go
scan_rr.go

loc: use float64 to get enough precision

---

edns.go
edns_test.go

OPT: add Z and SetZ methods

---

acceptfunc.go
dnssec.go
edns.go
privaterr.go
scan_rr.go
svcb.go
tsig_test.go
types.go

I went through the list and cleaned things up here and there.

small cleans from go report card

---

msg_helpers.go

EDNS0: Adding TCPKeepAlive to makeDataOpt

---

client.go

- Fix race condition in ExchangeContext.
- Implement suggestions from review in #1274

Fix race condition in ExchangeContext

---

README.md

Hi,
Would love to be added to the list of projects. We are extremely happy with the lib!
Johan

add fleetdeck project

---

.github/workflows/go.yml

Upgrade our test Go version to 1.17 and 1.18

---

labels.go

NextLabel: document neg. offset will panic

---

acceptfunc.go
client.go
doc.go
duplicate_generate.go
fuzz.go
listen_no_reuseport.go
listen_reuseport.go
msg.go
msg_generate.go
parse_test.go
svcb.go
tools.go
types_generate.go
udp.go
udp_test.go
udp_windows.go
xfr.go

Run gofmt -w -s *.go

---

README.md

First, thank you for this project.
Submitting two completely free projects that wouldn't be possible without this library.

readme: add some very thankful users

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yml

Updates actions and updates go to 1.19.x

Update actions & add go 1.19.x and 1.20.x to go workflow

---

msg_helpers.go

I missed this pattern in #1432. These seem to be the only two occurrences.
Updates #1432

Use cloneSlice in unpackDataA and unpackDataAAAA

---

README.md

Added [NineDNS](https://github.com/wintbiit/NineDNS) to the list of users.
`NineDNS` is a flexible DNS server thats offers DNS resolution based on the question source.
`NineDNS` aims to provide a flexible way to resolve DNS records.
You can match different question source by cidr, port, protocol, and so on.
Clients can use different dns resolve based on their network environment.
For example, you can filter clients by cidr, and resolve different dns records for them.
Moreover, NineDNS supports retrieving DNS records from remote databases such as MySQL or PostgreSQL.
It's easy to manage DNS records in a centralized way.

docs: added NineDNS to Users List

---

msg.go
scan.go
xfr.go

chore: fix some comments

---

README.md

Add [ifconfig.es](https://ifconfig.es) to the list of users

Add ifconfig.es to the list of users

---

README.md

Add the check-soa program, which uses the library

---

scan.go
types.go
update.go

Put docs on the ANY type, also reference this from the dynamic updates stuff.

Document how to create RRs without rdata

---

.github/workflows/go.yml
scan.go

A comment concerning newline while scanning

---

msg.go
types.go

Add the rcode DSO-TYPE Not Implemented / DSOTYPENI from RFC8490 (DNS Stateful Operations)

Add the rcode DSO-TYPE Not Implemented / RFC8490

---

README.md

Added OwNS (NS for VPN users)
